## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x008000-0x008423 (SNES $C08000), 1060 bytes.

import
  ./[assembler, opcodes]

proc generateBootCode*(): seq[uint8] =
  ## Assemble the region at file 0x008000 from disassembled source.
  let nodes = @[
    label("loc_C08000"),
    instr("STZ", amAbsolute, 0x4200),  # $C08000: STZ $4200
    instr("STZ", amDirectPage, 0x0),  # $C08003: STZ $00
    instr("LDX", amImmediateX, 0x0),  # $C08005: LDX #$00
    instr("LDY", amImmediateX, 0x1),  # $C08007: LDY #$01
    instr("REP", amImmediate8, 0x30),  # $C08009: REP #$30
    instr("LDA", amImmediateM, 0x1FFE),  # $C0800B: LDA #$1FFE
    instr("MVN", amBlockMove, 0x0),  # $C0800E: MVN $00,$00
    instr("TXS", amImplied),  # $C08011: TXS
    instr("LDA", amImmediateM, 0x1F00),  # $C08012: LDA #$1F00
    instr("TCD", amImplied),  # $C08015: TCD
    instr("SEP", amImmediate8, 0x20),  # $C08016: SEP #$20
    instr("LDA", amImmediateM, 0x80),  # $C08018: LDA #$80
    instr("STA", amAbsolute, 0x2100),  # $C0801A: STA $2100
    instr("STA", amAbsolute, 0xD),  # $C0801D: STA $000D
    instr("STZ", amAbsolute, 0x2101),  # $C08020: STZ $2101
    instr("STZ", amAbsolute, 0x2102),  # $C08023: STZ $2102
    instr("STZ", amAbsolute, 0x2103),  # $C08026: STZ $2103
    instr("STZ", amAbsolute, 0x2105),  # $C08029: STZ $2105
    instr("STZ", amAbsolute, 0x2106),  # $C0802C: STZ $2106
    instr("STZ", amAbsolute, 0x2107),  # $C0802F: STZ $2107
    instr("STZ", amAbsolute, 0x2108),  # $C08032: STZ $2108
    instr("STZ", amAbsolute, 0x2109),  # $C08035: STZ $2109
    instr("STZ", amAbsolute, 0x210A),  # $C08038: STZ $210A
    instr("STZ", amAbsolute, 0x210B),  # $C0803B: STZ $210B
    instr("STZ", amAbsolute, 0x210C),  # $C0803E: STZ $210C
    instr("STZ", amAbsolute, 0x210D),  # $C08041: STZ $210D
    instr("STZ", amAbsolute, 0x210D),  # $C08044: STZ $210D
    instr("STZ", amAbsolute, 0x210E),  # $C08047: STZ $210E
    instr("STZ", amAbsolute, 0x210E),  # $C0804A: STZ $210E
    instr("STZ", amAbsolute, 0x210F),  # $C0804D: STZ $210F
    instr("STZ", amAbsolute, 0x210F),  # $C08050: STZ $210F
    instr("STZ", amAbsolute, 0x2110),  # $C08053: STZ $2110
    instr("STZ", amAbsolute, 0x2110),  # $C08056: STZ $2110
    instr("STZ", amAbsolute, 0x2111),  # $C08059: STZ $2111
    instr("STZ", amAbsolute, 0x2111),  # $C0805C: STZ $2111
    instr("STZ", amAbsolute, 0x2112),  # $C0805F: STZ $2112
    instr("STZ", amAbsolute, 0x2112),  # $C08062: STZ $2112
    instr("STZ", amAbsolute, 0x2113),  # $C08065: STZ $2113
    instr("STZ", amAbsolute, 0x2113),  # $C08068: STZ $2113
    instr("STZ", amAbsolute, 0x2114),  # $C0806B: STZ $2114
    instr("STZ", amAbsolute, 0x2114),  # $C0806E: STZ $2114
    instr("LDA", amImmediateM, 0x80),  # $C08071: LDA #$80
    instr("STA", amAbsolute, 0x2115),  # $C08073: STA $2115
    instr("STZ", amAbsolute, 0x2116),  # $C08076: STZ $2116
    instr("STZ", amAbsolute, 0x2117),  # $C08079: STZ $2117
    instr("STZ", amAbsolute, 0x211A),  # $C0807C: STZ $211A
    instr("STZ", amAbsolute, 0x211B),  # $C0807F: STZ $211B
    instr("LDA", amImmediateM, 0x1),  # $C08082: LDA #$01
    instr("STA", amAbsolute, 0x211B),  # $C08084: STA $211B
    instr("STZ", amAbsolute, 0x211C),  # $C08087: STZ $211C
    instr("STZ", amAbsolute, 0x211C),  # $C0808A: STZ $211C
    instr("STZ", amAbsolute, 0x211D),  # $C0808D: STZ $211D
    instr("STZ", amAbsolute, 0x211D),  # $C08090: STZ $211D
    instr("STZ", amAbsolute, 0x211E),  # $C08093: STZ $211E
    instr("STA", amAbsolute, 0x211E),  # $C08096: STA $211E
    instr("STZ", amAbsolute, 0x211F),  # $C08099: STZ $211F
    instr("STZ", amAbsolute, 0x211F),  # $C0809C: STZ $211F
    instr("STZ", amAbsolute, 0x2120),  # $C0809F: STZ $2120
    instr("STZ", amAbsolute, 0x2120),  # $C080A2: STZ $2120
    instr("STZ", amAbsolute, 0x2121),  # $C080A5: STZ $2121
    instr("STZ", amAbsolute, 0x2123),  # $C080A8: STZ $2123
    instr("STZ", amAbsolute, 0x2124),  # $C080AB: STZ $2124
    instr("STZ", amAbsolute, 0x2125),  # $C080AE: STZ $2125
    instr("STZ", amAbsolute, 0x2126),  # $C080B1: STZ $2126
    instr("STZ", amAbsolute, 0x2127),  # $C080B4: STZ $2127
    instr("STZ", amAbsolute, 0x2128),  # $C080B7: STZ $2128
    instr("STZ", amAbsolute, 0x2129),  # $C080BA: STZ $2129
    instr("STZ", amAbsolute, 0x212A),  # $C080BD: STZ $212A
    instr("STZ", amAbsolute, 0x212B),  # $C080C0: STZ $212B
    instr("LDA", amImmediateM, 0x1F),  # $C080C3: LDA #$1F
    instr("STA", amAbsolute, 0x212C),  # $C080C5: STA $212C
    instr("STZ", amAbsolute, 0x212D),  # $C080C8: STZ $212D
    instr("STZ", amAbsolute, 0x212E),  # $C080CB: STZ $212E
    instr("STZ", amAbsolute, 0x212F),  # $C080CE: STZ $212F
    instr("STZ", amAbsolute, 0x2130),  # $C080D1: STZ $2130
    instr("STZ", amAbsolute, 0x2131),  # $C080D4: STZ $2131
    instr("LDA", amImmediateM, 0xE0),  # $C080D7: LDA #$E0
    instr("STA", amAbsolute, 0x2132),  # $C080D9: STA $2132
    instr("STZ", amAbsolute, 0x2133),  # $C080DC: STZ $2133
    instr("LDA", amImmediateM, 0xFF),  # $C080DF: LDA #$FF
    instr("STA", amAbsolute, 0x4202),  # $C080E1: STA $4202
    instr("STZ", amAbsolute, 0x4202),  # $C080E4: STZ $4202
    instr("STZ", amAbsolute, 0x4203),  # $C080E7: STZ $4203
    instr("STZ", amAbsolute, 0x4204),  # $C080EA: STZ $4204
    instr("STZ", amAbsolute, 0x4205),  # $C080ED: STZ $4205
    instr("STZ", amAbsolute, 0x4206),  # $C080F0: STZ $4206
    instr("STZ", amAbsolute, 0x4207),  # $C080F3: STZ $4207
    instr("STZ", amAbsolute, 0x4208),  # $C080F6: STZ $4208
    instr("STZ", amAbsolute, 0x4209),  # $C080F9: STZ $4209
    instr("STZ", amAbsolute, 0x420A),  # $C080FC: STZ $420A
    instr("STZ", amAbsolute, 0x420B),  # $C080FF: STZ $420B
    instr("STZ", amAbsolute, 0x420C),  # $C08102: STZ $420C
    instr("LDA", amImmediateM, 0x1),  # $C08105: LDA #$01
    instr("STA", amAbsolute, 0x420D),  # $C08107: STA $420D
    instr("REP", amImmediate8, 0x30),  # $C0810A: REP #$30
    instr("LDA", amImmediateM, 0xDFFF),  # $C0810C: LDA #$DFFF
    instr("MVN", amBlockMove, 0x7E7E),  # $C0810F: MVN $7E,$7E
    instr("LDA", amImmediateM, 0x2000),  # $C08112: LDA #$2000
    instr("STA", amAbsolute, 0xA1),  # $C08115: STA $00A1
    instr("STA", amAbsolute, 0xA3),  # $C08118: STA $00A3
    instr("LDA", amImmediateM, 0xFFFF),  # $C0811B: LDA #$FFFF
    instr("STA", amAbsolute, 0x2402),  # $C0811E: STA $2402
    instr("LDA", amImmediateM, 0x1234),  # $C08121: LDA #$1234
    instr("STA", amAbsolute, 0x24),  # $C08124: STA $0024
    instr("LDA", amImmediateM, 0x5678),  # $C08127: LDA #$5678
    instr("STA", amAbsolute, 0x26),  # $C0812A: STA $0026
    instr("LDA", amImmediateM, 0x1),  # $C0812D: LDA #$0001
    instr("STA", amAbsolute, 0x2E),  # $C08130: STA $002E
    instr("LDA", amImmediateM, 0x851B),  # $C08133: LDA #$851B
    instr("STA", amAbsolute, 0x20),  # $C08136: STA $0020
    instr("JSL", amAbsoluteLong, 0xC08B19),  # $C08139: JSL $C08B19
    instr("JML", amAbsoluteLong, 0xC0B99A),  # $C0813D: JML $C0B99A
    instr("CLC", amImplied),  # $C08141: CLC
    instr("XCE", amImplied),  # $C08142: XCE
    instrTo("JML", amAbsoluteLong, "loc_C08000"),  # $C08143: JML $C08000
    instrTo("JML", amAbsoluteLong, "loc_C08170"),  # $C08147: JML $C08170
    instrTo("JML", amAbsoluteLong, "loc_C0814F"),  # $C0814B: JML $C0814F
    label("loc_C0814F"),
    instr("PHP", amImplied),  # $C0814F: PHP
    instr("REP", amImmediate8, 0x30),  # $C08150: REP #$30
    instr("PHA", amImplied),  # $C08152: PHA
    instr("PHX", amImplied),  # $C08153: PHX
    instr("PHY", amImplied),  # $C08154: PHY
    instr("PHD", amImplied),  # $C08155: PHD
    instr("PEA", amAbsolute, 0x0),  # $C08156: PEA $0000
    instr("PLD", amImplied),  # $C08159: PLD
    instr("PHB", amImplied),  # $C0815A: PHB
    instr("PEA", amAbsolute, 0x0),  # $C0815B: PEA $0000
    instr("PLB", amImplied),  # $C0815E: PLB
    instr("PLB", amImplied),  # $C0815F: PLB
    instr("SEP", amImmediate8, 0x20),  # $C08160: SEP #$20
    instr("LDA", amAbsolute, 0x4211),  # $C08162: LDA $4211
    instrTo("BMI", amRelative8, "loc_C08183"),  # $C08165: BMI +28
    instr("REP", amImmediate8, 0x30),  # $C08167: REP #$30
    instr("PLB", amImplied),  # $C08169: PLB
    instr("PLD", amImplied),  # $C0816A: PLD
    instr("PLY", amImplied),  # $C0816B: PLY
    instr("PLX", amImplied),  # $C0816C: PLX
    instr("PLA", amImplied),  # $C0816D: PLA
    instr("PLP", amImplied),  # $C0816E: PLP
    instr("RTI", amImplied),  # $C0816F: RTI
    label("loc_C08170"),
    instr("PHP", amImplied),  # $C08170: PHP
    instr("REP", amImmediate8, 0x30),  # $C08171: REP #$30
    instr("PHA", amImplied),  # $C08173: PHA
    instr("PHX", amImplied),  # $C08174: PHX
    instr("PHY", amImplied),  # $C08175: PHY
    instr("PHD", amImplied),  # $C08176: PHD
    instr("PEA", amAbsolute, 0x0),  # $C08177: PEA $0000
    instr("PLD", amImplied),  # $C0817A: PLD
    instr("PHB", amImplied),  # $C0817B: PHB
    instr("PEA", amAbsolute, 0x0),  # $C0817C: PEA $0000
    instr("PLB", amImplied),  # $C0817F: PLB
    instr("PLB", amImplied),  # $C08180: PLB
    instr("SEP", amImmediate8, 0x20),  # $C08181: SEP #$20
    label("loc_C08183"),
    instr("LDA", amAbsolute, 0x4210),  # $C08183: LDA $4210
    instr("STZ", amAbsolute, 0x420C),  # $C08186: STZ $420C
    instr("LDA", amImmediateM, 0x80),  # $C08189: LDA #$80
    instr("STA", amAbsolute, 0x2100),  # $C0818B: STA $2100
    instr("INC", amDirectPage, 0x2B),  # $C0818E: INC $2B
    instr("INC", amDirectPage, 0x2),  # $C08190: INC $02
    instr("REP", amImmediate8, 0x20),  # $C08192: REP #$20
    instr("SEP", amImmediate8, 0x10),  # $C08194: SEP #$10
    instr("LDX", amDirectPage, 0x2C),  # $C08196: LDX $2C
    instrTo("BEQ", amRelative8, "loc_C081C8"),  # $C08198: BEQ +46
    instr("LDY", amImmediateX, 0x0),  # $C0819A: LDY #$00
    instr("STZ", amAbsolute, 0x2102),  # $C0819C: STZ $2102
    instr("STY", amAbsolute, 0x4300),  # $C0819F: STY $4300
    instr("STY", amAbsolute, 0x4304),  # $C081A2: STY $4304
    instr("LDY", amImmediateX, 0x4),  # $C081A5: LDY #$04
    instr("STY", amAbsolute, 0x4301),  # $C081A7: STY $4301
    instr("LDA", amImmediateM, 0x500),  # $C081AA: LDA #$0500
    instr("LDX", amDirectPage, 0x2C),  # $C081AD: LDX $2C
    instr("DEX", amImplied),  # $C081AF: DEX
    instrTo("BEQ", amRelative8, "loc_C081B5"),  # $C081B0: BEQ +3
    instr("LDA", amImmediateM, 0x800),  # $C081B2: LDA #$0800
    label("loc_C081B5"),
    instr("STA", amAbsolute, 0x4302),  # $C081B5: STA $4302
    instr("LDA", amImmediateM, 0x220),  # $C081B8: LDA #$0220
    instr("STA", amAbsolute, 0x4305),  # $C081BB: STA $4305
    instr("LDY", amImmediateX, 0x1),  # $C081BE: LDY #$01
    instr("STY", amAbsolute, 0x420B),  # $C081C0: STY $420B
    instr("CLC", amImplied),  # $C081C3: CLC
    instr("ADC", amDirectPage, 0x99),  # $C081C4: ADC $99
    instr("STA", amDirectPage, 0x99),  # $C081C6: STA $99
    label("loc_C081C8"),
    instr("LDX", amAbsolute, 0x30),  # $C081C8: LDX $0030
    instrTo("BEQ", amRelative8, "loc_C081F7"),  # $C081CB: BEQ +42
    instr("LDA", amAbsoluteX, 0x8F94),  # $C081CD: LDA $8F94,X
    instr("STA", amAbsolute, 0x4302),  # $C081D0: STA $4302
    instr("LDY", amAbsoluteX, 0x8F96),  # $C081D3: LDY $8F96,X
    instr("STY", amAbsolute, 0x2121),  # $C081D6: STY $2121
    instr("LDA", amImmediateM, 0x2200),  # $C081D9: LDA #$2200
    instr("STA", amAbsolute, 0x4300),  # $C081DC: STA $4300
    instr("LDY", amImmediateX, 0x0),  # $C081DF: LDY #$00
    instr("STY", amAbsolute, 0x4304),  # $C081E1: STY $4304
    instr("STY", amAbsolute, 0x30),  # $C081E4: STY $0030
    instr("LDA", amAbsoluteX, 0x8F92),  # $C081E7: LDA $8F92,X
    instr("STA", amAbsolute, 0x4305),  # $C081EA: STA $4305
    instr("LDY", amImmediateX, 0x1),  # $C081ED: LDY #$01
    instr("STY", amAbsolute, 0x420B),  # $C081EF: STY $420B
    instr("CLC", amImplied),  # $C081F2: CLC
    instr("ADC", amDirectPage, 0x99),  # $C081F3: ADC $99
    instr("STA", amDirectPage, 0x99),  # $C081F5: STA $99
    label("loc_C081F7"),
    instr("SEP", amImmediate8, 0x20),  # $C081F7: SEP #$20
    instr("LDA", amDirectPage, 0x28),  # $C081F9: LDA $28
    instrTo("BEQ", amRelative8, "loc_C0821F"),  # $C081FB: BEQ +34
    instr("DEC", amDirectPage, 0x2A),  # $C081FD: DEC $2A
    instrTo("BPL", amRelative8, "loc_C0821F"),  # $C081FF: BPL +30
    instr("LDA", amDirectPage, 0x29),  # $C08201: LDA $29
    instr("STA", amDirectPage, 0x2A),  # $C08203: STA $2A
    instr("LDA", amDirectPage, 0xD),  # $C08205: LDA $0D
    instr("AND", amImmediateM, 0xF),  # $C08207: AND #$0F
    instr("CLC", amImplied),  # $C08209: CLC
    instr("ADC", amDirectPage, 0x28),  # $C0820A: ADC $28
    instrTo("BPL", amRelative8, "loc_C08215"),  # $C0820C: BPL +7
    instr("STZ", amAbsolute, 0x1F),  # $C0820E: STZ $001F
    instr("LDA", amImmediateM, 0x80),  # $C08211: LDA #$80
    instrTo("BRA", amRelative8, "loc_C0821B"),  # $C08213: BRA +6
    label("loc_C08215"),
    instr("CMP", amImmediateM, 0x10),  # $C08215: CMP #$10
    instrTo("BCC", amRelative8, "loc_C0821D"),  # $C08217: BCC +4
    instr("LDA", amImmediateM, 0xF),  # $C08219: LDA #$0F
    label("loc_C0821B"),
    instr("STZ", amDirectPage, 0x28),  # $C0821B: STZ $28
    label("loc_C0821D"),
    instr("STA", amDirectPage, 0xD),  # $C0821D: STA $0D
    label("loc_C0821F"),
    instr("REP", amImmediate8, 0x10),  # $C0821F: REP #$10
    instr("LDA", amDirectPage, 0xD),  # $C08221: LDA $0D
    instr("STA", amAbsolute, 0x2100),  # $C08223: STA $2100
    instr("LDA", amDirectPage, 0x10),  # $C08226: LDA $10
    instr("STA", amAbsolute, 0x2106),  # $C08228: STA $2106
    instr("LDY", amDirectPage, 0x15),  # $C0822B: LDY $15
    instr("STY", amAbsolute, 0x210B),  # $C0822D: STY $210B
    instr("LDY", amDirectPage, 0x17),  # $C08230: LDY $17
    instr("LDY", amImmediateX, 0xFF),  # $C08232: LDY #$00FF
    instr("STY", amAbsolute, 0x2128),  # $C08235: STY $2128
    instr("REP", amImmediate8, 0x20),  # $C08238: REP #$20
    instr("SEP", amImmediate8, 0x10),  # $C0823A: SEP #$10
    instr("LDX", amDirectPage, 0x1),  # $C0823C: LDX $01
    instrTo("BRA", amRelative8, "loc_C08272"),  # $C0823E: BRA +50
    label("loc_C08240"),
    instr("LDY", amAbsoluteX, 0x400),  # $C08240: LDY $0400,X
    instr("LDA", amAbsoluteY, 0x8FB0),  # $C08243: LDA $8FB0,Y
    instr("STA", amAbsolute, 0x4300),  # $C08246: STA $4300
    instr("LDA", amAbsoluteY, 0x8FB2),  # $C08249: LDA $8FB2,Y
    instr("STA", amAbsolute, 0x2115),  # $C0824C: STA $2115
    instr("LDA", amAbsoluteX, 0x401),  # $C0824F: LDA $0401,X
    instr("STA", amAbsolute, 0x4305),  # $C08252: STA $4305
    instr("LDA", amAbsoluteX, 0x403),  # $C08255: LDA $0403,X
    instr("STA", amAbsolute, 0x4302),  # $C08258: STA $4302
    instr("LDY", amAbsoluteX, 0x405),  # $C0825B: LDY $0405,X
    instr("STY", amAbsolute, 0x4304),  # $C0825E: STY $4304
    instr("LDA", amAbsoluteX, 0x406),  # $C08261: LDA $0406,X
    instr("STA", amAbsolute, 0x2116),  # $C08264: STA $2116
    instr("TXA", amImplied),  # $C08267: TXA
    instr("CLC", amImplied),  # $C08268: CLC
    instr("ADC", amImmediateM, 0x8),  # $C08269: ADC #$0008
    instr("TAX", amImplied),  # $C0826C: TAX
    instr("LDY", amImmediateX, 0x1),  # $C0826D: LDY #$01
    instr("STY", amAbsolute, 0x420B),  # $C0826F: STY $420B
    label("loc_C08272"),
    instr("CPX", amDirectPage, 0x0),  # $C08272: CPX $00
    instrTo("BNE", amRelative8, "loc_C08240"),  # $C08274: BNE -54
    instr("STX", amDirectPage, 0x1),  # $C08276: STX $01
    instr("SEP", amImmediate8, 0x20),  # $C08278: SEP #$20
    instr("LDA", amDirectPage, 0x2C),  # $C0827A: LDA $2C
    instrTo("BNE", amRelative8, "loc_C08281"),  # $C0827C: BNE +3
    instrTo("JMP", amAbsolute, "loc_C08334"),  # $C0827E: JMP $8334
    label("loc_C08281"),
    instr("DEC", amAccumulator),  # $C08281: DEC A
    instrTo("BNE", amRelative8, "loc_C082D6"),  # $C08282: BNE +82
    instr("LDA", amDirectPage, 0x41),  # $C08284: LDA $41
    instr("STA", amAbsolute, 0x210D),  # $C08286: STA $210D
    instr("LDA", amDirectPage, 0x42),  # $C08289: LDA $42
    instr("STA", amAbsolute, 0x210D),  # $C0828B: STA $210D
    instr("LDA", amDirectPage, 0x45),  # $C0828E: LDA $45
    instr("STA", amAbsolute, 0x210E),  # $C08290: STA $210E
    instr("LDA", amDirectPage, 0x46),  # $C08293: LDA $46
    instr("STA", amAbsolute, 0x210E),  # $C08295: STA $210E
    instr("LDA", amDirectPage, 0x49),  # $C08298: LDA $49
    instr("STA", amAbsolute, 0x210F),  # $C0829A: STA $210F
    instr("LDA", amDirectPage, 0x4A),  # $C0829D: LDA $4A
    instr("STA", amAbsolute, 0x210F),  # $C0829F: STA $210F
    instr("LDA", amDirectPage, 0x4D),  # $C082A2: LDA $4D
    instr("STA", amAbsolute, 0x2110),  # $C082A4: STA $2110
    instr("LDA", amDirectPage, 0x4E),  # $C082A7: LDA $4E
    instr("STA", amAbsolute, 0x2110),  # $C082A9: STA $2110
    instr("LDA", amDirectPage, 0x51),  # $C082AC: LDA $51
    instr("STA", amAbsolute, 0x2111),  # $C082AE: STA $2111
    instr("LDA", amDirectPage, 0x52),  # $C082B1: LDA $52
    instr("STA", amAbsolute, 0x2111),  # $C082B3: STA $2111
    instr("LDA", amDirectPage, 0x55),  # $C082B6: LDA $55
    instr("STA", amAbsolute, 0x2112),  # $C082B8: STA $2112
    instr("LDA", amDirectPage, 0x56),  # $C082BB: LDA $56
    instr("STA", amAbsolute, 0x2112),  # $C082BD: STA $2112
    instr("LDA", amDirectPage, 0x59),  # $C082C0: LDA $59
    instr("STA", amAbsolute, 0x2113),  # $C082C2: STA $2113
    instr("LDA", amDirectPage, 0x5A),  # $C082C5: LDA $5A
    instr("STA", amAbsolute, 0x2113),  # $C082C7: STA $2113
    instr("LDA", amDirectPage, 0x5D),  # $C082CA: LDA $5D
    instr("STA", amAbsolute, 0x2114),  # $C082CC: STA $2114
    instr("LDA", amDirectPage, 0x5E),  # $C082CF: LDA $5E
    instr("STA", amAbsolute, 0x2114),  # $C082D1: STA $2114
    instrTo("BRA", amRelative8, "loc_C08334"),  # $C082D4: BRA +94
    label("loc_C082D6"),
    instr("LDA", amDirectPage, 0x43),  # $C082D6: LDA $43
    instr("STA", amAbsolute, 0x210D),  # $C082D8: STA $210D
    instr("LDA", amDirectPage, 0x44),  # $C082DB: LDA $44
    instr("STA", amAbsolute, 0x210D),  # $C082DD: STA $210D
    instr("LDA", amDirectPage, 0x47),  # $C082E0: LDA $47
    instr("STA", amAbsolute, 0x210E),  # $C082E2: STA $210E
    instr("LDA", amDirectPage, 0x48),  # $C082E5: LDA $48
    instr("STA", amAbsolute, 0x210E),  # $C082E7: STA $210E
    instr("LDA", amDirectPage, 0x4B),  # $C082EA: LDA $4B
    instr("STA", amAbsolute, 0x210F),  # $C082EC: STA $210F
    instr("LDA", amDirectPage, 0x4C),  # $C082EF: LDA $4C
    instr("STA", amAbsolute, 0x210F),  # $C082F1: STA $210F
    instr("LDA", amDirectPage, 0x4F),  # $C082F4: LDA $4F
    instr("STA", amAbsolute, 0x2110),  # $C082F6: STA $2110
    instr("LDA", amDirectPage, 0x50),  # $C082F9: LDA $50
    instr("STA", amAbsolute, 0x2110),  # $C082FB: STA $2110
    instr("LDA", amDirectPage, 0x53),  # $C082FE: LDA $53
    instr("STA", amAbsolute, 0x2111),  # $C08300: STA $2111
    instr("LDA", amDirectPage, 0x54),  # $C08303: LDA $54
    instr("STA", amAbsolute, 0x2111),  # $C08305: STA $2111
    instr("LDA", amDirectPage, 0x57),  # $C08308: LDA $57
    instr("STA", amAbsolute, 0x2112),  # $C0830A: STA $2112
    instr("LDA", amDirectPage, 0x58),  # $C0830D: LDA $58
    instr("STA", amAbsolute, 0x2112),  # $C0830F: STA $2112
    instr("LDA", amDirectPage, 0x5B),  # $C08312: LDA $5B
    instr("STA", amAbsolute, 0x2113),  # $C08314: STA $2113
    instr("LDA", amDirectPage, 0x5C),  # $C08317: LDA $5C
    instr("STA", amAbsolute, 0x2113),  # $C08319: STA $2113
    instr("LDA", amDirectPage, 0x5F),  # $C0831C: LDA $5F
    instr("STA", amAbsolute, 0x2114),  # $C0831E: STA $2114
    instr("LDA", amDirectPage, 0x60),  # $C08321: LDA $60
    instr("STA", amAbsolute, 0x2114),  # $C08323: STA $2114
    instr("REP", amImmediate8, 0x20),  # $C08326: REP #$20
    instr("LDA", amAbsolute, 0x31),  # $C08328: LDA $0031
    instr("STA", amAbsolute, 0x61),  # $C0832B: STA $0061
    instr("LDA", amAbsolute, 0x33),  # $C0832E: LDA $0033
    instr("STA", amAbsolute, 0x63),  # $C08331: STA $0063
    label("loc_C08334"),
    instr("LDY", amImmediateX, 0x0),  # $C08334: LDY #$00
    instr("STY", amDirectPage, 0x2C),  # $C08336: STY $2C
    instr("LDX", amDirectPage, 0xD),  # $C08338: LDX $0D
    instrTo("BMI", amRelative8, "loc_C0834B"),  # $C0833A: BMI +15
    instr("LDX", amDirectPage, 0x1A),  # $C0833C: LDX $1A
    instr("STX", amAbsolute, 0x212C),  # $C0833E: STX $212C
    instr("LDX", amDirectPage, 0x1B),  # $C08341: LDX $1B
    instr("STX", amAbsolute, 0x212D),  # $C08343: STX $212D
    instr("LDX", amDirectPage, 0x1F),  # $C08346: LDX $1F
    instr("STX", amAbsolute, 0x420C),  # $C08348: STX $420C
    label("loc_C0834B"),
    instr("JSR", amAbsolute, 0x8501),  # $C0834B: JSR $8501
    instr("REP", amImmediate8, 0x30),  # $C0834E: REP #$30
    instr("STZ", amDirectPage, 0x99),  # $C08350: STZ $99
    instr("LDA", amAbsolute, 0x22),  # $C08352: LDA $0022
    instrTo("BNE", amRelative8, "loc_C0836D"),  # $C08355: BNE +22
    instr("INC", amAbsolute, 0x22),  # $C08357: INC $0022
    instr("PHB", amImplied),  # $C0835A: PHB
    instr("PEA", amAbsolute, 0x7E7E),  # $C0835B: PEA $7E7E
    instr("PLB", amImplied),  # $C0835E: PLB
    instr("PLB", amImplied),  # $C0835F: PLB
    instr("PHD", amImplied),  # $C08360: PHD
    instr("PEA", amAbsolute, 0x200),  # $C08361: PEA $0200
    instr("PLD", amImplied),  # $C08364: PLD
    instr("JSR", amAbsolute, 0x8518),  # $C08365: JSR $8518
    instr("PLD", amImplied),  # $C08368: PLD
    instr("PLB", amImplied),  # $C08369: PLB
    instr("STZ", amAbsolute, 0x22),  # $C0836A: STZ $0022
    label("loc_C0836D"),
    instr("LDA", amImmediateM, 0x2000),  # $C0836D: LDA #$2000
    instr("CMP", amDirectPage, 0xA3),  # $C08370: CMP $A3
    instrTo("BNE", amRelative8, "loc_C08377"),  # $C08372: BNE +3
    instr("LDA", amImmediateM, 0x2200),  # $C08374: LDA #$2200
    label("loc_C08377"),
    instr("STA", amDirectPage, 0xA3),  # $C08377: STA $A3
    instr("STA", amDirectPage, 0xA1),  # $C08379: STA $A1
    instr("LDA", amImmediateM, 0x0),  # $C0837B: LDA #$0000
    instr("STA", amAbsoluteLong, 0x7E9E2B),  # $C0837E: STA $7E9E2B
    instr("STZ", amDirectPage, 0xAB),  # $C08382: STZ $AB
    instr("INC", amDirectPage, 0xA7),  # $C08384: INC $A7
    instrTo("BNE", amRelative8, "loc_C0838A"),  # $C08386: BNE +2
    instr("INC", amDirectPage, 0xA9),  # $C08388: INC $A9
    label("loc_C0838A"),
    instr("PLB", amImplied),  # $C0838A: PLB
    instr("PLD", amImplied),  # $C0838B: PLD
    instr("PLY", amImplied),  # $C0838C: PLY
    instr("PLX", amImplied),  # $C0838D: PLX
    instr("PLA", amImplied),  # $C0838E: PLA
    instr("PLP", amImplied),  # $C0838F: PLP
    instr("RTI", amImplied),  # $C08390: RTI
    instr("SEP", amImmediate8, 0x20),  # $C08391: SEP #$20
    instr("LDA", amImmediateM, 0x30),  # $C08393: LDA #$30
    instr("STA", amAbsoluteLong, 0x307FF0),  # $C08395: STA $307FF0
    instr("INC", amAccumulator),  # $C08399: INC A
    instr("STA", amAbsoluteLong, 0x317FF0),  # $C0839A: STA $317FF0
    instr("CMP", amAbsoluteLong, 0x307FF0),  # $C0839E: CMP $307FF0
    instrTo("BEQ", amRelative8, "loc_C083B2"),  # $C083A2: BEQ +14
    instr("INC", amAccumulator),  # $C083A4: INC A
    instr("STA", amAbsoluteLong, 0x327FF0),  # $C083A5: STA $327FF0
    instr("CMP", amAbsoluteLong, 0x307FF0),  # $C083A9: CMP $307FF0
    instrTo("BEQ", amRelative8, "loc_C083B2"),  # $C083AD: BEQ +3
    instr("STA", amAbsolute, 0xA36),  # $C083AF: STA $0A36
    label("loc_C083B2"),
    instr("REP", amImmediate8, 0x30),  # $C083B2: REP #$30
    instr("LDA", amAbsolute, 0xA36),  # $C083B4: LDA $0A36
    instr("RTL", amImplied),  # $C083B7: RTL
    label("loc_C083B8"),
    instr("REP", amImmediate8, 0x30),  # $C083B8: REP #$30
    instr("LDA", amImmediateM, 0x0),  # $C083BA: LDA #$0000
    instr("STA", amAbsolute, 0x7B),  # $C083BD: STA $007B
    instr("RTL", amImplied),  # $C083C0: RTL
    instr("REP", amImmediate8, 0x30),  # $C083C1: REP #$30
    instr("LDA", amDirectPage, 0xE),  # $C083C3: LDA $0E
    instr("STA", amAbsolute, 0x85),  # $C083C5: STA $0085
    instr("LDA", amDirectPage, 0x10),  # $C083C8: LDA $10
    instr("STA", amAbsolute, 0x87),  # $C083CA: STA $0087
    instr("LDA", amAbsolute, 0x65),  # $C083CD: LDA $0065
    instr("STA", amAbsolute, 0x8B),  # $C083D0: STA $008B
    instr("LDA", amImmediateM, 0x1),  # $C083D3: LDA #$0001
    instr("STA", amAbsolute, 0x89),  # $C083D6: STA $0089
    instr("LDA", amImmediateM, 0x8000),  # $C083D9: LDA #$8000
    instr("ORA", amAbsolute, 0x7B),  # $C083DC: ORA $007B
    instr("STA", amAbsolute, 0x7B),  # $C083DF: STA $007B
    instr("RTL", amImplied),  # $C083E2: RTL
    instr("REP", amImmediate8, 0x30),  # $C083E3: REP #$30
    instr("LDA", amAbsolute, 0x7B),  # $C083E5: LDA $007B
    instr("AND", amImmediateM, 0x4000),  # $C083E8: AND #$4000
    instrTo("BNE", amRelative8, "loc_C0841A"),  # $C083EB: BNE +45
    instr("LDA", amDpIndirectLong, 0xE),  # $C083ED: LDA [$0E]
    instr("AND", amImmediateM, 0xFF),  # $C083EF: AND #$00FF
    instrTo("BEQ", amRelative8, "loc_C083B8"),  # $C083F2: BEQ -60
    instr("STA", amAbsolute, 0x81),  # $C083F4: STA $0081
    instr("LDY", amImmediateX, 0x1),  # $C083F7: LDY #$0001
    instr("LDA", amDpIndirectLongY, 0xE),  # $C083FA: LDA [$0E],Y
    instr("STA", amAbsolute, 0x83),  # $C083FC: STA $0083
    instr("LDA", amDirectPage, 0xE),  # $C083FF: LDA $0E
    instr("STA", amAbsolute, 0x7D),  # $C08401: STA $007D
    instr("LDA", amDirectPage, 0x10),  # $C08404: LDA $10
    instr("STA", amAbsolute, 0x7F),  # $C08406: STA $007F
    instr("LDA", amDpIndirectLongY, 0xE),  # $C08409: LDA [$0E],Y
    instr("STA", amAbsolute, 0x77),  # $C0840B: STA $0077
    instr("STA", amAbsolute, 0x79),  # $C0840E: STA $0079
    instr("LDA", amImmediateM, 0x4000),  # $C08411: LDA #$4000
    instr("ORA", amAbsolute, 0x7B),  # $C08414: ORA $007B
    instr("STA", amAbsolute, 0x7B),  # $C08417: STA $007B
    label("loc_C0841A"),
    instr("RTL", amImplied),  # $C0841A: RTL
    instr("REP", amImmediate8, 0x30),  # $C0841B: REP #$30
    instr("LDA", amDirectPage, 0x7B),  # $C0841D: LDA $7B
    instr("BEQ", amRelative8, 0x2A),  # $C0841F: BEQ +42
    instr("AND", amImmediateM, 0x4000),  # $C08421: AND #$4000
  ]
  result = assemble(nodes, 0xC08000'u32,
                    FlagState(m8: true, x8: true, emulation: false))
