## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000EDA-0x000EE3 (SNES $C00EDA), 10 bytes.

import
  ./[assembler, opcodes]

proc generateCode000EDA*(): seq[uint8] =
  ## Assemble the region at file 0x000EDA from disassembled source.
  let nodes = @[
    instr("ORA", amImmediateM, 0x12A5),  # $C00EDA: ORA #$12A5
    instr("ORA", amImmediateM, 0x2000),  # $C00EDD: ORA #$2000
    instr("STA", amDirectPage, 0x12),  # $C00EE0: STA $12
    instr("BRA", amRelative8, 0x2),  # $C00EE2: BRA +2
  ]
  result = assemble(nodes, 0xC00EDA'u32,
                    FlagState(m8: false, x8: false, emulation: false))
