## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000EE6-0x000F66 (SNES $C00EE6), 129 bytes.

import
  ./[assembler, opcodes]

proc generateCode000EE6*(): seq[uint8] =
  ## Assemble the region at file 0x000EE6 from disassembled source.
  let nodes = @[
    instr("TXA", amImplied),  # $C00EE6: TXA
    instr("ASL", amAccumulator),  # $C00EE7: ASL A
    instr("TAY", amImplied),  # $C00EE8: TAY
    instr("LDA", amDirectPage, 0x12),  # $C00EE9: LDA $12
    instr("STA", amDpIndirectY, 0x1C),  # $C00EEB: STA ($1C),Y
    instr("INX", amImplied),  # $C00EED: INX
    instr("TXA", amImplied),  # $C00EEE: TXA
    instr("AND", amImmediateM, 0x3F),  # $C00EEF: AND #$003F
    instr("TAX", amImplied),  # $C00EF2: TAX
    instr("STX", amDirectPage, 0x16),  # $C00EF3: STX $16
    instr("LDA", amDirectPage, 0x20),  # $C00EF5: LDA $20
    instr("INC", amAccumulator),  # $C00EF7: INC A
    instr("STA", amDirectPage, 0x20),  # $C00EF8: STA $20
    instr("LDA", amDirectPage, 0x14),  # $C00EFA: LDA $14
    instr("STA", amDirectPage, 0x2),  # $C00EFC: STA $02
    instr("INC", amDirectPage, 0x2),  # $C00EFE: INC $02
    instr("LDA", amDirectPage, 0x2),  # $C00F00: LDA $02
    instr("STA", amDirectPage, 0x14),  # $C00F02: STA $14
    instr("LDA", amDirectPage, 0x2),  # $C00F04: LDA $02
    instr("CMP", amImmediateM, 0x22),  # $C00F06: CMP #$0022
    instrTo("BCS", amRelative8, "loc_C00F10"),  # $C00F09: BCS +5
    instrTo("BEQ", amRelative8, "loc_C00F10"),  # $C00F0B: BEQ +3
    instr("JMP", amAbsolute, 0xE93),  # $C00F0D: JMP $0E93
    label("loc_C00F10"),
    instr("LDA", amDirectPage, 0x4),  # $C00F10: LDA $04
    instr("AND", amImmediateM, 0x1F),  # $C00F12: AND #$001F
    instr("ASL", amAccumulator),  # $C00F15: ASL A
    instr("ASL", amAccumulator),  # $C00F16: ASL A
    instr("ASL", amAccumulator),  # $C00F17: ASL A
    instr("ASL", amAccumulator),  # $C00F18: ASL A
    instr("ASL", amAccumulator),  # $C00F19: ASL A
    instr("STA", amDirectPage, 0x2),  # $C00F1A: STA $02
    instr("LDA", amDirectPage, 0x1E),  # $C00F1C: LDA $1E
    instr("STA", amDirectPage, 0x6),  # $C00F1E: STA $06
    instr("PHB", amImplied),  # $C00F20: PHB
    instr("SEP", amImmediate8, 0x20),  # $C00F21: SEP #$20
    instr("PLA", amImplied),  # $C00F23: PLA
    instr("STA", amDirectPage, 0x8),  # $C00F24: STA $08
    instr("STZ", amDirectPage, 0x9),  # $C00F26: STZ $09
    instr("REP", amImmediate8, 0x20),  # $C00F28: REP #$20
    instr("LDA", amDirectPage, 0x6),  # $C00F2A: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C00F2C: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C00F2E: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C00F30: STA $10
    instr("LDA", amDirectPage, 0x2),  # $C00F32: LDA $02
    instr("CLC", amImplied),  # $C00F34: CLC
    instr("ADC", amImmediateM, 0x3800),  # $C00F35: ADC #$3800
    instr("TAY", amImplied),  # $C00F38: TAY
    instr("LDX", amImmediateX, 0x40),  # $C00F39: LDX #$0040
    instr("SEP", amImmediate8, 0x20),  # $C00F3C: SEP #$20
    instr("LDA", amImmediateM, 0x0),  # $C00F3E: LDA #$00
    instr("JSL", amAbsoluteLong, 0xC08616),  # $C00F40: JSL $C08616
    instr("LDA", amDirectPage, 0x1E),  # $C00F44: LDA $1E
    instr("CLC", amImplied),  # $C00F46: CLC
    instr("ADC", amImmediateM, 0x40),  # $C00F47: ADC #$40
    instr("BRK", amImmediate8, 0x85),  # $C00F49: BRK #$85
    instr("ASL", amDirectPage, 0x8B),  # $C00F4B: ASL $8B
    instr("SEP", amImmediate8, 0x20),  # $C00F4D: SEP #$20
    instr("PLA", amImplied),  # $C00F4F: PLA
    instr("STA", amDirectPage, 0x8),  # $C00F50: STA $08
    instr("STZ", amDirectPage, 0x9),  # $C00F52: STZ $09
    instr("REP", amImmediate8, 0x20),  # $C00F54: REP #$20
    instr("LDA", amDirectPage, 0x6),  # $C00F56: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C00F58: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C00F5A: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C00F5C: STA $10
    instr("LDA", amDirectPage, 0x2),  # $C00F5E: LDA $02
    instr("CLC", amImplied),  # $C00F60: CLC
    instr("ADC", amImmediateM, 0x3C00),  # $C00F61: ADC #$3C00
    instr("TAY", amImplied),  # $C00F64: TAY
  ]
  result = assemble(nodes, 0xC00EE6'u32,
                    FlagState(m8: false, x8: false, emulation: false))

  # Trailing bytes the linear decode could not cover as whole
  # instructions (region boundary is arbitrary). Declared as data.
  # TODO: refine the region boundary when the code map improves.
  result.add @[0xA2'u8, 0x40'u8]
