## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000FCB-0x001047 (SNES $C00FCB), 125 bytes.

import
  ./[assembler, opcodes]

proc generateCode000FCB*(): seq[uint8] =
  ## Assemble the region at file 0x000FCB from disassembled source.
  let nodes = @[
    instr("REP", amImmediate8, 0x31),  # $C00FCB: REP #$31
    instr("PHD", amImplied),  # $C00FCD: PHD
    instr("PHA", amImplied),  # $C00FCE: PHA
    instr("TDC", amImplied),  # $C00FCF: TDC
    instr("ADC", amImmediateM, 0xFFDE),  # $C00FD0: ADC #$FFDE
    instr("TCD", amImplied),  # $C00FD3: TCD
    instr("PLA", amImplied),  # $C00FD4: PLA
    instr("TXY", amImplied),  # $C00FD5: TXY
    instr("STY", amDirectPage, 0x20),  # $C00FD6: STY $20
    instr("STA", amDirectPage, 0x4),  # $C00FD8: STA $04
    instr("LDA", amAbsolute, 0x436C),  # $C00FDA: LDA $436C
    instrTo("BEQ", amRelative8, "loc_C00FE6"),  # $C00FDD: BEQ +7
    instr("TYX", amImplied),  # $C00FDF: TYX
    instr("LDA", amDirectPage, 0x4),  # $C00FE0: LDA $04
    instr("JSL", amAbsoluteLong, 0xEFE07C),  # $C00FE2: JSL $EFE07C
    label("loc_C00FE6"),
    instr("LDA", amImmediateM, 0x80),  # $C00FE6: LDA #$0080
    instr("JSL", amAbsoluteLong, 0xC086DE),  # $C00FE9: JSL $C086DE
    instr("STA", amDirectPage, 0x1E),  # $C00FED: STA $1E
    instr("CLC", amImplied),  # $C00FEF: CLC
    instr("ADC", amImmediateM, 0x40),  # $C00FF0: ADC #$0040
    instr("STA", amDirectPage, 0x1C),  # $C00FF3: STA $1C
    instr("LDY", amDirectPage, 0x20),  # $C00FF5: LDY $20
    instr("TYA", amImplied),  # $C00FF7: TYA
    instr("DEC", amAccumulator),  # $C00FF8: DEC A
    instr("STA", amDirectPage, 0x20),  # $C00FF9: STA $20
    instr("LDA", amDirectPage, 0x4),  # $C00FFB: LDA $04
    instr("LSR", amAccumulator),  # $C00FFD: LSR A
    instr("LSR", amAccumulator),  # $C00FFE: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00FFF: AND #$000F
    instr("ASL", amAccumulator),  # $C01002: ASL A
    instr("CLC", amImplied),  # $C01003: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C01004: ADC #$F000
    instr("STA", amDirectPage, 0x1A),  # $C01007: STA $1A
    instr("LDA", amDirectPage, 0x4),  # $C01009: LDA $04
    instr("AND", amImmediateM, 0x3),  # $C0100B: AND #$0003
    instr("PHA", amImplied),  # $C0100E: PHA
    instr("LDA", amDirectPage, 0x20),  # $C0100F: LDA $20
    instr("AND", amImmediateM, 0x3),  # $C01011: AND #$0003
    instr("ASL", amAccumulator),  # $C01014: ASL A
    instr("ASL", amAccumulator),  # $C01015: ASL A
    instr("STA", amDirectPage, 0x2),  # $C01016: STA $02
    instr("LDA", amDirectPage, 0x20),  # $C01018: LDA $20
    instr("LSR", amAccumulator),  # $C0101A: LSR A
    instr("LSR", amAccumulator),  # $C0101B: LSR A
    instr("AND", amImmediateM, 0xF),  # $C0101C: AND #$000F
    instr("ASL", amAccumulator),  # $C0101F: ASL A
    instr("ASL", amAccumulator),  # $C01020: ASL A
    instr("ASL", amAccumulator),  # $C01021: ASL A
    instr("ASL", amAccumulator),  # $C01022: ASL A
    instr("ASL", amAccumulator),  # $C01023: ASL A
    instr("TAY", amImplied),  # $C01024: TAY
    instr("LDA", amDpIndirectY, 0x1A),  # $C01025: LDA ($1A),Y
    instr("ASL", amAccumulator),  # $C01027: ASL A
    instr("ASL", amAccumulator),  # $C01028: ASL A
    instr("ASL", amAccumulator),  # $C01029: ASL A
    instr("ASL", amAccumulator),  # $C0102A: ASL A
    instr("CLC", amImplied),  # $C0102B: CLC
    instr("ADC", amDirectPage, 0x2),  # $C0102C: ADC $02
    instr("PLY", amImplied),  # $C0102E: PLY
    instr("STY", amDirectPage, 0x2),  # $C0102F: STY $02
    instr("CLC", amImplied),  # $C01031: CLC
    instr("ADC", amDirectPage, 0x2),  # $C01032: ADC $02
    instr("TAY", amImplied),  # $C01034: TAY
    instr("STY", amDirectPage, 0x18),  # $C01035: STY $18
    instr("LDA", amDirectPage, 0x20),  # $C01037: LDA $20
    instr("AND", amImmediateM, 0x1F),  # $C01039: AND #$001F
    instr("TAX", amImplied),  # $C0103C: TAX
    instr("STX", amDirectPage, 0x16),  # $C0103D: STX $16
    instr("LDA", amImmediateM, 0x0),  # $C0103F: LDA #$0000
    instr("STA", amDirectPage, 0x2),  # $C01042: STA $02
    instr("STA", amDirectPage, 0x14),  # $C01044: STA $14
    instr("BRA", amRelative8, 0x74),  # $C01046: BRA +116
  ]
  result = assemble(nodes, 0xC00FCB'u32,
                    FlagState(m8: false, x8: false, emulation: false))
