## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000000-0x000171 (SNES $C00000), 370 bytes.

import
  ./[assembler, opcodes]

proc generateCode000000*(): seq[uint8] =
  ## Assemble the region at file 0x000000 from disassembled source.
  let nodes = @[
    instr("STZ", amAbsolute, 0x280C),  # $C00000: STZ $280C
    instr("LDX", amImmediateX, 0x280C),  # $C00003: LDX #$280C
    instr("LDY", amImmediateX, 0x280D),  # $C00006: LDY #$280D
    instr("LDA", amImmediateM, 0x3B),  # $C00009: LDA #$003B
    instr("MVN", amBlockMove, 0x7E7E),  # $C0000C: MVN $7E,$7E
    instr("LDA", amImmediateM, 0x280C),  # $C0000F: LDA #$280C
    instr("RTS", amImplied),  # $C00012: RTS
    label("loc_C00013"),
    instr("REP", amImmediate8, 0x31),  # $C00013: REP #$31
    instr("LDA", amImmediateM, 0x9),  # $C00015: LDA #$0009
    instr("JSL", amAbsoluteLong, 0xC08D79),  # $C00018: JSL $C08D79
    instr("LDY", amImmediateX, 0x0),  # $C0001C: LDY #$0000
    instr("LDX", amImmediateX, 0x3800),  # $C0001F: LDX #$3800
    instr("LDA", amImmediateM, 0x1),  # $C00022: LDA #$0001
    instr("JSL", amAbsoluteLong, 0xC08D9E),  # $C00025: JSL $C08D9E
    instr("LDY", amImmediateX, 0x2000),  # $C00029: LDY #$2000
    instr("LDX", amImmediateX, 0x5800),  # $C0002C: LDX #$5800
    instr("LDA", amImmediateM, 0x1),  # $C0002F: LDA #$0001
    instr("JSL", amAbsoluteLong, 0xC08DDE),  # $C00032: JSL $C08DDE
    instr("LDY", amImmediateX, 0x6000),  # $C00036: LDY #$6000
    instr("LDX", amImmediateX, 0x7C00),  # $C00039: LDX #$7C00
    instr("LDA", amImmediateM, 0x0),  # $C0003C: LDA #$0000
    instr("JSL", amAbsoluteLong, 0xC08E1C),  # $C0003F: JSL $C08E1C
    instr("LDA", amImmediateM, 0x62),  # $C00043: LDA #$0062
    instr("JSL", amAbsoluteLong, 0xC08D92),  # $C00046: JSL $C08D92
    instr("RTL", amImplied),  # $C0004A: RTL
    instr("REP", amImmediate8, 0x31),  # $C0004B: REP #$31
    instr("PHD", amImplied),  # $C0004D: PHD
    instr("TDC", amImplied),  # $C0004E: TDC
    instr("ADC", amImmediateM, 0xFFEE),  # $C0004F: ADC #$FFEE
    instr("TCD", amImplied),  # $C00052: TCD
    instr("LDA", amImmediateM, 0x0),  # $C00053: LDA #$0000
    instr("STA", amDirectPage, 0x6),  # $C00056: STA $06
    instr("LDA", amImmediateM, 0x7F),  # $C00058: LDA #$007F
    instr("STA", amDirectPage, 0x8),  # $C0005B: STA $08
    instrTo("JSL", amAbsoluteLong, "loc_C00013"),  # $C0005D: JSL $C00013
    instr("LDA", amImmediateM, 0x0),  # $C00061: LDA #$0000
    instr("STA", amDpIndirectLong, 0x6),  # $C00064: STA [$06]
    instr("LDA", amDirectPage, 0x6),  # $C00066: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C00068: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C0006A: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C0006C: STA $10
    instr("LDY", amImmediateX, 0x0),  # $C0006E: LDY #$0000
    instr("TYX", amImplied),  # $C00071: TYX
    instr("SEP", amImmediate8, 0x20),  # $C00072: SEP #$20
    instr("LDA", amImmediateM, 0x3),  # $C00074: LDA #$03
    instr("JSL", amAbsoluteLong, 0xC08616),  # $C00076: JSL $C08616
    instr("LDA", amImmediateM, 0xFF),  # $C0007A: LDA #$FF
    instr("SBC", amAbsoluteLongX, 0x43708D),  # $C0007C: SBC $43708D,X
    instr("STA", amAbsolute, 0x436E),  # $C00080: STA $436E
    instr("PLD", amImplied),  # $C00083: PLD
    instr("RTL", amImplied),  # $C00084: RTL
    instr("REP", amImmediate8, 0x31),  # $C00085: REP #$31
    instr("PHD", amImplied),  # $C00087: PHD
    instr("TDC", amImplied),  # $C00088: TDC
    instr("ADC", amImmediateM, 0xFFE2),  # $C00089: ADC #$FFE2
    instr("TCD", amImplied),  # $C0008C: TCD
    instr("STZ", amAbsolute, 0x4472),  # $C0008D: STZ $4472
    instr("LDA", amAbsolute, 0x4372),  # $C00090: LDA $4372
    instr("ASL", amAccumulator),  # $C00093: ASL A
    instr("ASL", amAccumulator),  # $C00094: ASL A
    instr("STA", amDirectPage, 0x1C),  # $C00095: STA $1C
    instr("LDA", amImmediateM, 0x121B),  # $C00097: LDA #$121B
    instr("STA", amDirectPage, 0xA),  # $C0009A: STA $0A
    instr("LDA", amImmediateM, 0xEF),  # $C0009C: LDA #$00EF
    instr("STA", amDirectPage, 0xC),  # $C0009F: STA $0C
    instr("LDA", amDirectPage, 0x1C),  # $C000A1: LDA $1C
    instr("CLC", amImplied),  # $C000A3: CLC
    instr("ADC", amDirectPage, 0xA),  # $C000A4: ADC $0A
    instr("STA", amDirectPage, 0xA),  # $C000A6: STA $0A
    instr("LDY", amImmediateX, 0x2),  # $C000A8: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0xA),  # $C000AB: LDA [$0A],Y
    instr("TAY", amImplied),  # $C000AD: TAY
    instr("LDA", amDpIndirectLong, 0xA),  # $C000AE: LDA [$0A]
    instr("STA", amDirectPage, 0x6),  # $C000B0: STA $06
    instr("STY", amDirectPage, 0x8),  # $C000B2: STY $08
    instr("LDA", amDirectPage, 0x6),  # $C000B4: LDA $06
    instr("STA", amDirectPage, 0x18),  # $C000B6: STA $18
    instr("LDA", amDirectPage, 0x8),  # $C000B8: LDA $08
    instr("STA", amDirectPage, 0x1A),  # $C000BA: STA $1A
    instr("LDA", amDpIndirectLong, 0x6),  # $C000BC: LDA [$06]
    instr("AND", amImmediateM, 0xFF),  # $C000BE: AND #$00FF
    instrTo("BNE", amRelative8, "loc_C000C6"),  # $C000C1: BNE +3
    instrTo("JMP", amAbsolute, "loc_C00170"),  # $C000C3: JMP $0170
    label("loc_C000C6"),
    instr("LDA", amImmediateM, 0x11CB),  # $C000C6: LDA #$11CB
    instr("STA", amDirectPage, 0xA),  # $C000C9: STA $0A
    instr("LDA", amImmediateM, 0xEF),  # $C000CB: LDA #$00EF
    instr("STA", amDirectPage, 0xC),  # $C000CE: STA $0C
    instr("LDA", amDirectPage, 0x1C),  # $C000D0: LDA $1C
    instr("CLC", amImplied),  # $C000D2: CLC
    instr("ADC", amDirectPage, 0xA),  # $C000D3: ADC $0A
    instr("STA", amDirectPage, 0xA),  # $C000D5: STA $0A
    instr("LDY", amImmediateX, 0x2),  # $C000D7: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0xA),  # $C000DA: LDA [$0A],Y
    instr("TAY", amImplied),  # $C000DC: TAY
    instr("LDA", amDpIndirectLong, 0xA),  # $C000DD: LDA [$0A]
    instr("STA", amDirectPage, 0x6),  # $C000DF: STA $06
    instr("STY", amDirectPage, 0x8),  # $C000E1: STY $08
    instr("LDA", amDirectPage, 0x6),  # $C000E3: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C000E5: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C000E7: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C000E9: STA $10
    instr("LDA", amImmediateM, 0xC000),  # $C000EB: LDA #$C000
    instr("STA", amDirectPage, 0x12),  # $C000EE: STA $12
    instr("LDA", amImmediateM, 0x7E),  # $C000F0: LDA #$007E
    instr("STA", amDirectPage, 0x14),  # $C000F3: STA $14
    instr("JSL", amAbsoluteLong, 0xC41A9E),  # $C000F5: JSL $C41A9E
    instr("LDA", amDirectPage, 0x18),  # $C000F9: LDA $18
    instr("STA", amDirectPage, 0x6),  # $C000FB: STA $06
    instr("LDA", amDirectPage, 0x1A),  # $C000FD: LDA $1A
    instr("STA", amDirectPage, 0x8),  # $C000FF: STA $08
    instr("LDA", amDpIndirectLong, 0x6),  # $C00101: LDA [$06]
    instr("AND", amImmediateM, 0xFF),  # $C00103: AND #$00FF
    instr("STA", amAbsolute, 0x4472),  # $C00106: STA $4472
    instr("STA", amDirectPage, 0x2),  # $C00109: STA $02
    instr("INC", amDirectPage, 0x6),  # $C0010B: INC $06
    instr("LDY", amImmediateX, 0x0),  # $C0010D: LDY #$0000
    instr("STY", amDirectPage, 0x16),  # $C00110: STY $16
    instrTo("BRA", amRelative8, "loc_C0016B"),  # $C00112: BRA +87
    label("loc_C00114"),
    instr("TYA", amImplied),  # $C00114: TYA
    instr("ASL", amAccumulator),  # $C00115: ASL A
    instr("ASL", amAccumulator),  # $C00116: ASL A
    instr("ASL", amAccumulator),  # $C00117: ASL A
    instr("ASL", amAccumulator),  # $C00118: ASL A
    instr("CLC", amImplied),  # $C00119: CLC
    instr("ADC", amImmediateM, 0x43DC),  # $C0011A: ADC #$43DC
    instr("TAX", amImplied),  # $C0011D: TAX
    instr("LDA", amDirectPage, 0x6),  # $C0011E: LDA $06
    instr("STA", amDirectPage, 0xA),  # $C00120: STA $0A
    instr("LDA", amDirectPage, 0x8),  # $C00122: LDA $08
    instr("STA", amDirectPage, 0xC),  # $C00124: STA $0C
    instr("LDA", amDpIndirectLong, 0xA),  # $C00126: LDA [$0A]
    instr("AND", amImmediateM, 0xFF),  # $C00128: AND #$00FF
    instr("STA", amAbsoluteX, 0x0),  # $C0012B: STA $0000,X
    instr("SEP", amImmediate8, 0x20),  # $C0012E: SEP #$20
    instr("LDY", amImmediateX, 0x1),  # $C00130: LDY #$0001
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00133: LDA [$06],Y
    instr("REP", amImmediate8, 0x20),  # $C00135: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C00137: AND #$00FF
    instr("STA", amAbsoluteX, 0xA),  # $C0013A: STA $000A,X
    instr("STA", amAbsoluteX, 0x2),  # $C0013D: STA $0002,X
    instr("LDY", amImmediateX, 0x2),  # $C00140: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00143: LDA [$06],Y
    instr("STA", amAbsoluteX, 0x4),  # $C00145: STA $0004,X
    instr("LDY", amImmediateX, 0x4),  # $C00148: LDY #$0004
    instr("LDA", amDpIndirectLongY, 0x6),  # $C0014B: LDA [$06],Y
    instr("STA", amAbsoluteX, 0xE),  # $C0014D: STA $000E,X
    instr("STA", amAbsoluteX, 0x6),  # $C00150: STA $0006,X
    instr("LDY", amImmediateX, 0x6),  # $C00153: LDY #$0006
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00156: LDA [$06],Y
    instr("STA", amAbsoluteX, 0x8),  # $C00158: STA $0008,X
    instr("STZ", amAbsoluteX, 0xC),  # $C0015B: STZ $000C,X
    instr("LDA", amImmediateM, 0x8),  # $C0015E: LDA #$0008
    instr("CLC", amImplied),  # $C00161: CLC
    instr("ADC", amDirectPage, 0x6),  # $C00162: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C00164: STA $06
    instr("LDY", amDirectPage, 0x16),  # $C00166: LDY $16
    instr("INY", amImplied),  # $C00168: INY
    instr("STY", amDirectPage, 0x16),  # $C00169: STY $16
    label("loc_C0016B"),
    instr("TYA", amImplied),  # $C0016B: TYA
    instr("CMP", amDirectPage, 0x2),  # $C0016C: CMP $02
    instrTo("BCC", amRelative8, "loc_C00114"),  # $C0016E: BCC -92
    label("loc_C00170"),
    instr("PLD", amImplied),  # $C00170: PLD
    instr("RTS", amImplied),  # $C00171: RTS
  ]
  result = assemble(nodes, 0xC00000'u32,
                    FlagState(m8: false, x8: false, emulation: false))
