## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000A30-0x000E92 (SNES $C00A30), 1123 bytes.

import
  ./[assembler, opcodes]

proc generateCode000A30*(): seq[uint8] =
  ## Assemble the region at file 0x000A30 from disassembled source.
  let nodes = @[
    instr("LDA", amImmediateM, 0x200),  # $C00A30: LDA #$0200
    instr("STA", amDirectPage, 0x6),  # $C00A33: STA $06
    instr("PHB", amImplied),  # $C00A35: PHB
    instr("SEP", amImmediate8, 0x20),  # $C00A36: SEP #$20
    instr("PLA", amImplied),  # $C00A38: PLA
    instr("STA", amDirectPage, 0x8),  # $C00A39: STA $08
    instr("STZ", amDirectPage, 0x9),  # $C00A3B: STZ $09
    instr("REP", amImmediate8, 0x20),  # $C00A3D: REP #$20
    instr("LDA", amImmediateM, 0x40),  # $C00A3F: LDA #$0040
    instr("CLC", amImplied),  # $C00A42: CLC
    instr("ADC", amDirectPage, 0x6),  # $C00A43: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C00A45: STA $06
    instr("STA", amDirectPage, 0xE),  # $C00A47: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C00A49: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C00A4B: STA $10
    instr("LDX", amImmediateX, 0x1C0),  # $C00A4D: LDX #$01C0
    instr("LDA", amImmediateM, 0x4476),  # $C00A50: LDA #$4476
    instr("JSL", amAbsoluteLong, 0xC08ED2),  # $C00A53: JSL $C08ED2
    instr("LDA", amAbsolute, 0x4676),  # $C00A57: LDA $4676
    instrTo("BEQ", amRelative8, "loc_C00A75"),  # $C00A5A: BEQ +25
    instr("JSL", amAbsoluteLong, 0xC496F9),  # $C00A5C: JSL $C496F9
    instr("SEP", amImmediate8, 0x20),  # $C00A60: SEP #$20
    instr("LDA", amImmediateM, 0xFF),  # $C00A62: LDA #$FF
    instr("STA", amDirectPage, 0xE),  # $C00A64: STA $0E
    instr("LDX", amImmediateX, 0x200),  # $C00A66: LDX #$0200
    instr("REP", amImmediate8, 0x20),  # $C00A69: REP #$20
    instr("LDA", amImmediateM, 0x200),  # $C00A6B: LDA #$0200
    instr("JSL", amAbsoluteLong, 0xC08EFC),  # $C00A6E: JSL $C08EFC
    instr("STZ", amAbsolute, 0x4676),  # $C00A72: STZ $4676
    label("loc_C00A75"),
    instr("LDA", amAbsolute, 0xB4EF),  # $C00A75: LDA $B4EF
    instrTo("BEQ", amRelative8, "loc_C00A8E"),  # $C00A78: BEQ +20
    instr("JSL", amAbsoluteLong, 0xC496F9),  # $C00A7A: JSL $C496F9
    instr("SEP", amImmediate8, 0x20),  # $C00A7E: SEP #$20
    instr("STZ", amDirectPage, 0xE),  # $C00A80: STZ $0E
    instr("LDX", amImmediateX, 0x1E0),  # $C00A82: LDX #$01E0
    instr("REP", amImmediate8, 0x20),  # $C00A85: REP #$20
    instr("LDA", amImmediateM, 0x220),  # $C00A87: LDA #$0220
    instr("JSL", amAbsoluteLong, 0xC08EFC),  # $C00A8A: JSL $C08EFC
    label("loc_C00A8E"),
    instr("LDA", amImmediateM, 0x18),  # $C00A8E: LDA #$0018
    instr("JSL", amAbsoluteLong, 0xC0856B),  # $C00A91: JSL $C0856B
    instr("LDA", amDirectPage, 0x4),  # $C00A95: LDA $04
    instr("STA", amAbsolute, 0x436E),  # $C00A97: STA $436E
    instr("LDA", amDirectPage, 0x18),  # $C00A9A: LDA $18
    instr("STA", amAbsolute, 0x4370),  # $C00A9C: STA $4370
    instr("PLD", amImplied),  # $C00A9F: PLD
    instr("RTS", amImplied),  # $C00AA0: RTS
    instr("REP", amImmediate8, 0x31),  # $C00AA1: REP #$31
    instr("PHD", amImplied),  # $C00AA3: PHD
    instr("PHA", amImplied),  # $C00AA4: PHA
    instr("TDC", amImplied),  # $C00AA5: TDC
    instr("ADC", amImmediateM, 0xFFF2),  # $C00AA6: ADC #$FFF2
    instr("TCD", amImplied),  # $C00AA9: TCD
    instr("PLA", amImplied),  # $C00AAA: PLA
    instr("XBA", amImplied),  # $C00AAB: XBA
    instr("AND", amImmediateM, 0xFF),  # $C00AAC: AND #$00FF
    instr("STA", amDirectPage, 0x2),  # $C00AAF: STA $02
    instr("TXA", amImplied),  # $C00AB1: TXA
    instr("AND", amImmediateM, 0xFF80),  # $C00AB2: AND #$FF80
    instr("LSR", amAccumulator),  # $C00AB5: LSR A
    instr("LSR", amAccumulator),  # $C00AB6: LSR A
    instr("CLC", amImplied),  # $C00AB7: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00AB8: ADC $02
    instr("ASL", amAccumulator),  # $C00ABA: ASL A
    instr("TAX", amImplied),  # $C00ABB: TAX
    instr("LDA", amAbsoluteLongX, 0xD7B200),  # $C00ABC: LDA $D7B200,X
    instr("STA", amAbsolute, 0x438E),  # $C00AC0: STA $438E
    instr("PLD", amImplied),  # $C00AC3: PLD
    instr("RTL", amImplied),  # $C00AC4: RTL
    instr("REP", amImmediate8, 0x31),  # $C00AC5: REP #$31
    instr("PHD", amImplied),  # $C00AC7: PHD
    instr("PHA", amImplied),  # $C00AC8: PHA
    instr("TDC", amImplied),  # $C00AC9: TDC
    instr("ADC", amImmediateM, 0xFFE6),  # $C00ACA: ADC #$FFE6
    instr("TCD", amImplied),  # $C00ACD: TCD
    instr("PLA", amImplied),  # $C00ACE: PLA
    instr("STA", amDirectPage, 0x18),  # $C00ACF: STA $18
    instr("TXA", amImplied),  # $C00AD1: TXA
    instr("LSR", amAccumulator),  # $C00AD2: LSR A
    instr("LSR", amAccumulator),  # $C00AD3: LSR A
    instr("STA", amDirectPage, 0x4),  # $C00AD4: STA $04
    instr("LDA", amDirectPage, 0x18),  # $C00AD6: LDA $18
    instr("AND", amImmediateM, 0x8000),  # $C00AD8: AND #$8000
    instrTo("BEQ", amRelative8, "loc_C00AE9"),  # $C00ADB: BEQ +12
    instr("LDA", amDirectPage, 0x18),  # $C00ADD: LDA $18
    instr("LSR", amAccumulator),  # $C00ADF: LSR A
    instr("LSR", amAccumulator),  # $C00AE0: LSR A
    instr("ORA", amImmediateM, 0xE000),  # $C00AE1: ORA #$E000
    instr("TAY", amImplied),  # $C00AE4: TAY
    instr("STY", amDirectPage, 0x16),  # $C00AE5: STY $16
    instrTo("BRA", amRelative8, "loc_C00AF0"),  # $C00AE7: BRA +7
    label("loc_C00AE9"),
    instr("LDA", amDirectPage, 0x18),  # $C00AE9: LDA $18
    instr("LSR", amAccumulator),  # $C00AEB: LSR A
    instr("LSR", amAccumulator),  # $C00AEC: LSR A
    instr("TAY", amImplied),  # $C00AED: TAY
    instr("STY", amDirectPage, 0x16),  # $C00AEE: STY $16
    label("loc_C00AF0"),
    instr("TYA", amImplied),  # $C00AF0: TYA
    instr("AND", amImmediateM, 0xF),  # $C00AF1: AND #$000F
    instr("TAX", amImplied),  # $C00AF4: TAX
    instr("STX", amDirectPage, 0x18),  # $C00AF5: STX $18
    instr("TYA", amImplied),  # $C00AF7: TYA
    instr("SEP", amImmediate8, 0x20),  # $C00AF8: SEP #$20
    instr("STA", amAbsoluteX, 0x4390),  # $C00AFA: STA $4390,X
    instr("REP", amImmediate8, 0x20),  # $C00AFD: REP #$20
    instr("LDA", amDirectPage, 0x4),  # $C00AFF: LDA $04
    instr("AND", amImmediateM, 0xF),  # $C00B01: AND #$000F
    instr("STA", amDirectPage, 0x14),  # $C00B04: STA $14
    instr("TAX", amImplied),  # $C00B06: TAX
    instr("LDA", amDirectPage, 0x4),  # $C00B07: LDA $04
    instr("SEP", amImmediate8, 0x20),  # $C00B09: SEP #$20
    instr("STA", amAbsoluteX, 0x43A0),  # $C00B0B: STA $43A0,X
    instr("REP", amImmediate8, 0x20),  # $C00B0E: REP #$20
    instr("TYA", amImplied),  # $C00B10: TYA
    instr("LSR", amAccumulator),  # $C00B11: LSR A
    instr("LSR", amAccumulator),  # $C00B12: LSR A
    instr("LSR", amAccumulator),  # $C00B13: LSR A
    instr("STA", amDirectPage, 0x2),  # $C00B14: STA $02
    instr("LDA", amDirectPage, 0x4),  # $C00B16: LDA $04
    instr("AND", amImmediateM, 0xFFFC),  # $C00B18: AND #$FFFC
    instr("ASL", amAccumulator),  # $C00B1B: ASL A
    instr("ASL", amAccumulator),  # $C00B1C: ASL A
    instr("ASL", amAccumulator),  # $C00B1D: ASL A
    instr("CLC", amImplied),  # $C00B1E: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00B1F: ADC $02
    instr("TAX", amImplied),  # $C00B21: TAX
    instr("SEP", amImmediate8, 0x20),  # $C00B22: SEP #$20
    instr("LDA", amAbsoluteLongX, 0xD7A800),  # $C00B24: LDA $D7A800,X
    instr("LSR", amAccumulator),  # $C00B28: LSR A
    instr("LSR", amAccumulator),  # $C00B29: LSR A
    instr("LSR", amAccumulator),  # $C00B2A: LSR A
    instr("REP", amImmediate8, 0x20),  # $C00B2B: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C00B2D: AND #$00FF
    instr("STA", amDirectPage, 0x12),  # $C00B30: STA $12
    instr("LDA", amDirectPage, 0x14),  # $C00B32: LDA $14
    instr("ASL", amAccumulator),  # $C00B34: ASL A
    instr("ASL", amAccumulator),  # $C00B35: ASL A
    instr("ASL", amAccumulator),  # $C00B36: ASL A
    instr("ASL", amAccumulator),  # $C00B37: ASL A
    instr("ASL", amAccumulator),  # $C00B38: ASL A
    instr("CLC", amImplied),  # $C00B39: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C00B3A: ADC #$F000
    instr("STA", amDirectPage, 0x14),  # $C00B3D: STA $14
    instr("LDA", amDirectPage, 0x4),  # $C00B3F: LDA $04
    instr("CMP", amImmediateM, 0x140),  # $C00B41: CMP #$0140
    instrTo("BCC", amRelative8, "loc_C00B49"),  # $C00B44: BCC +3
    instrTo("JMP", amAbsolute, "loc_C00BC2"),  # $C00B46: JMP $0BC2
    label("loc_C00B49"),
    instr("LDX", amDirectPage, 0x18),  # $C00B49: LDX $18
    instr("STX", amDirectPage, 0x2),  # $C00B4B: STX $02
    instr("LDA", amDirectPage, 0x2),  # $C00B4D: LDA $02
    instr("STA", amDirectPage, 0x10),  # $C00B4F: STA $10
    instr("STZ", amDirectPage, 0xE),  # $C00B51: STZ $0E
    instrTo("BRA", amRelative8, "loc_C00BB9"),  # $C00B53: BRA +100
    label("loc_C00B55"),
    instr("TYA", amImplied),  # $C00B55: TYA
    instr("AND", amImmediateM, 0x7),  # $C00B56: AND #$0007
    instrTo("BNE", amRelative8, "loc_C00B7D"),  # $C00B59: BNE +34
    instr("TYA", amImplied),  # $C00B5B: TYA
    instr("LSR", amAccumulator),  # $C00B5C: LSR A
    instr("LSR", amAccumulator),  # $C00B5D: LSR A
    instr("LSR", amAccumulator),  # $C00B5E: LSR A
    instr("STA", amDirectPage, 0x2),  # $C00B5F: STA $02
    instr("LDA", amDirectPage, 0x4),  # $C00B61: LDA $04
    instr("AND", amImmediateM, 0xFFFC),  # $C00B63: AND #$FFFC
    instr("ASL", amAccumulator),  # $C00B66: ASL A
    instr("ASL", amAccumulator),  # $C00B67: ASL A
    instr("ASL", amAccumulator),  # $C00B68: ASL A
    instr("CLC", amImplied),  # $C00B69: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00B6A: ADC $02
    instr("TAX", amImplied),  # $C00B6C: TAX
    instr("SEP", amImmediate8, 0x20),  # $C00B6D: SEP #$20
    instr("LDA", amAbsoluteLongX, 0xD7A800),  # $C00B6F: LDA $D7A800,X
    instr("LSR", amAccumulator),  # $C00B73: LSR A
    instr("LSR", amAccumulator),  # $C00B74: LSR A
    instr("LSR", amAccumulator),  # $C00B75: LSR A
    instr("REP", amImmediate8, 0x20),  # $C00B76: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C00B78: AND #$00FF
    instr("STA", amDirectPage, 0x12),  # $C00B7B: STA $12
    label("loc_C00B7D"),
    instr("CPY", amImmediateX, 0x100),  # $C00B7D: CPY #$0100
    instrTo("BCS", amRelative8, "loc_C00B9D"),  # $C00B80: BCS +27
    instr("LDA", amAbsolute, 0x436E),  # $C00B82: LDA $436E
    instr("CMP", amDirectPage, 0x12),  # $C00B85: CMP $12
    instrTo("BNE", amRelative8, "loc_C00B9D"),  # $C00B87: BNE +20
    instr("LDX", amDirectPage, 0x4),  # $C00B89: LDX $04
    instr("TYA", amImplied),  # $C00B8B: TYA
    instr("JSR", amAbsolute, 0xA156),  # $C00B8C: JSR $A156
    instr("STA", amDirectPage, 0x18),  # $C00B8F: STA $18
    instr("LDA", amDirectPage, 0x10),  # $C00B91: LDA $10
    instr("STA", amDirectPage, 0x2),  # $C00B93: STA $02
    instr("ASL", amAccumulator),  # $C00B95: ASL A
    instr("TAY", amImplied),  # $C00B96: TAY
    instr("LDA", amDirectPage, 0x18),  # $C00B97: LDA $18
    instr("STA", amDpIndirectY, 0x14),  # $C00B99: STA ($14),Y
    instrTo("BRA", amRelative8, "loc_C00BA8"),  # $C00B9B: BRA +11
    label("loc_C00B9D"),
    instr("LDA", amDirectPage, 0x10),  # $C00B9D: LDA $10
    instr("STA", amDirectPage, 0x2),  # $C00B9F: STA $02
    instr("ASL", amAccumulator),  # $C00BA1: ASL A
    instr("TAY", amImplied),  # $C00BA2: TAY
    instr("LDA", amImmediateM, 0x0),  # $C00BA3: LDA #$0000
    instr("STA", amDpIndirectY, 0x14),  # $C00BA6: STA ($14),Y
    label("loc_C00BA8"),
    instr("LDA", amDirectPage, 0x2),  # $C00BA8: LDA $02
    instr("INC", amAccumulator),  # $C00BAA: INC A
    instr("AND", amImmediateM, 0xF),  # $C00BAB: AND #$000F
    instr("STA", amDirectPage, 0x2),  # $C00BAE: STA $02
    instr("STA", amDirectPage, 0x10),  # $C00BB0: STA $10
    instr("LDY", amDirectPage, 0x16),  # $C00BB2: LDY $16
    instr("INY", amImplied),  # $C00BB4: INY
    instr("STY", amDirectPage, 0x16),  # $C00BB5: STY $16
    instr("INC", amDirectPage, 0xE),  # $C00BB7: INC $0E
    label("loc_C00BB9"),
    instr("LDA", amDirectPage, 0xE),  # $C00BB9: LDA $0E
    instr("CMP", amImmediateM, 0x10),  # $C00BBB: CMP #$0010
    instrTo("BCC", amRelative8, "loc_C00B55"),  # $C00BBE: BCC -107
    instrTo("BRA", amRelative8, "loc_C00BDA"),  # $C00BC0: BRA +24
    label("loc_C00BC2"),
    instr("LDA", amImmediateM, 0x0),  # $C00BC2: LDA #$0000
    instr("STA", amDirectPage, 0x18),  # $C00BC5: STA $18
    instrTo("BRA", amRelative8, "loc_C00BD5"),  # $C00BC7: BRA +12
    label("loc_C00BC9"),
    instr("ASL", amAccumulator),  # $C00BC9: ASL A
    instr("TAY", amImplied),  # $C00BCA: TAY
    instr("LDA", amImmediateM, 0x0),  # $C00BCB: LDA #$0000
    instr("STA", amDpIndirectY, 0x14),  # $C00BCE: STA ($14),Y
    instr("LDA", amDirectPage, 0x18),  # $C00BD0: LDA $18
    instr("INC", amAccumulator),  # $C00BD2: INC A
    instr("STA", amDirectPage, 0x18),  # $C00BD3: STA $18
    label("loc_C00BD5"),
    instr("CMP", amImmediateM, 0x10),  # $C00BD5: CMP #$0010
    instrTo("BCC", amRelative8, "loc_C00BC9"),  # $C00BD8: BCC -17
    label("loc_C00BDA"),
    instr("PLD", amImplied),  # $C00BDA: PLD
    instr("RTS", amImplied),  # $C00BDB: RTS
    instr("REP", amImmediate8, 0x31),  # $C00BDC: REP #$31
    instr("PHD", amImplied),  # $C00BDE: PHD
    instr("PHA", amImplied),  # $C00BDF: PHA
    instr("TDC", amImplied),  # $C00BE0: TDC
    instr("ADC", amImmediateM, 0xFFE4),  # $C00BE1: ADC #$FFE4
    instr("TCD", amImplied),  # $C00BE4: TCD
    instr("PLA", amImplied),  # $C00BE5: PLA
    instr("LSR", amAccumulator),  # $C00BE6: LSR A
    instr("LSR", amAccumulator),  # $C00BE7: LSR A
    instr("STA", amDirectPage, 0x4),  # $C00BE8: STA $04
    instr("TXA", amImplied),  # $C00BEA: TXA
    instr("AND", amImmediateM, 0x8000),  # $C00BEB: AND #$8000
    instrTo("BEQ", amRelative8, "loc_C00BFB"),  # $C00BEE: BEQ +11
    instr("TXA", amImplied),  # $C00BF0: TXA
    instr("LSR", amAccumulator),  # $C00BF1: LSR A
    instr("LSR", amAccumulator),  # $C00BF2: LSR A
    instr("ORA", amImmediateM, 0xE000),  # $C00BF3: ORA #$E000
    instr("TAY", amImplied),  # $C00BF6: TAY
    instr("STY", amDirectPage, 0x1A),  # $C00BF7: STY $1A
    instrTo("BRA", amRelative8, "loc_C00C01"),  # $C00BF9: BRA +6
    label("loc_C00BFB"),
    instr("TXA", amImplied),  # $C00BFB: TXA
    instr("LSR", amAccumulator),  # $C00BFC: LSR A
    instr("LSR", amAccumulator),  # $C00BFD: LSR A
    instr("TAY", amImplied),  # $C00BFE: TAY
    instr("STY", amDirectPage, 0x1A),  # $C00BFF: STY $1A
    label("loc_C00C01"),
    instr("LDA", amDirectPage, 0x4),  # $C00C01: LDA $04
    instr("AND", amImmediateM, 0xF),  # $C00C03: AND #$000F
    instr("STA", amDirectPage, 0x18),  # $C00C06: STA $18
    instr("TAX", amImplied),  # $C00C08: TAX
    instr("LDA", amDirectPage, 0x4),  # $C00C09: LDA $04
    instr("SEP", amImmediate8, 0x20),  # $C00C0B: SEP #$20
    instr("STA", amAbsoluteX, 0x43B0),  # $C00C0D: STA $43B0,X
    instr("REP", amImmediate8, 0x20),  # $C00C10: REP #$20
    instr("TYA", amImplied),  # $C00C12: TYA
    instr("AND", amImmediateM, 0xF),  # $C00C13: AND #$000F
    instr("TAX", amImplied),  # $C00C16: TAX
    instr("STX", amDirectPage, 0x16),  # $C00C17: STX $16
    instr("TYA", amImplied),  # $C00C19: TYA
    instr("SEP", amImmediate8, 0x20),  # $C00C1A: SEP #$20
    instr("STA", amAbsoluteX, 0x43C0),  # $C00C1C: STA $43C0,X
    instr("REP", amImmediate8, 0x20),  # $C00C1F: REP #$20
    instr("LDA", amDirectPage, 0x4),  # $C00C21: LDA $04
    instr("LSR", amAccumulator),  # $C00C23: LSR A
    instr("LSR", amAccumulator),  # $C00C24: LSR A
    instr("LSR", amAccumulator),  # $C00C25: LSR A
    instr("STA", amDirectPage, 0x2),  # $C00C26: STA $02
    instr("TYA", amImplied),  # $C00C28: TYA
    instr("AND", amImmediateM, 0xFFFC),  # $C00C29: AND #$FFFC
    instr("ASL", amAccumulator),  # $C00C2C: ASL A
    instr("ASL", amAccumulator),  # $C00C2D: ASL A
    instr("ASL", amAccumulator),  # $C00C2E: ASL A
    instr("CLC", amImplied),  # $C00C2F: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00C30: ADC $02
    instr("TAX", amImplied),  # $C00C32: TAX
    instr("SEP", amImmediate8, 0x20),  # $C00C33: SEP #$20
    instr("LDA", amAbsoluteLongX, 0xD7A800),  # $C00C35: LDA $D7A800,X
    instr("LSR", amAccumulator),  # $C00C39: LSR A
    instr("LSR", amAccumulator),  # $C00C3A: LSR A
    instr("LSR", amAccumulator),  # $C00C3B: LSR A
    instr("REP", amImmediate8, 0x20),  # $C00C3C: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C00C3E: AND #$00FF
    instr("STA", amDirectPage, 0x14),  # $C00C41: STA $14
    instr("LDA", amDirectPage, 0x18),  # $C00C43: LDA $18
    instr("ASL", amAccumulator),  # $C00C45: ASL A
    instr("CLC", amImplied),  # $C00C46: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C00C47: ADC #$F000
    instr("STA", amDirectPage, 0x12),  # $C00C4A: STA $12
    instr("LDA", amDirectPage, 0x4),  # $C00C4C: LDA $04
    instr("CMP", amImmediateM, 0x100),  # $C00C4E: CMP #$0100
    instrTo("BCC", amRelative8, "loc_C00C56"),  # $C00C51: BCC +3
    instrTo("JMP", amAbsolute, "loc_C00CD5"),  # $C00C53: JMP $0CD5
    label("loc_C00C56"),
    instr("LDX", amDirectPage, 0x16),  # $C00C56: LDX $16
    instr("TXA", amImplied),  # $C00C58: TXA
    instr("ASL", amAccumulator),  # $C00C59: ASL A
    instr("ASL", amAccumulator),  # $C00C5A: ASL A
    instr("ASL", amAccumulator),  # $C00C5B: ASL A
    instr("ASL", amAccumulator),  # $C00C5C: ASL A
    instr("STA", amDirectPage, 0x2),  # $C00C5D: STA $02
    instr("STA", amDirectPage, 0x10),  # $C00C5F: STA $10
    instr("STZ", amDirectPage, 0xE),  # $C00C61: STZ $0E
    instrTo("BRA", amRelative8, "loc_C00CCC"),  # $C00C63: BRA +103
    label("loc_C00C65"),
    instr("TYA", amImplied),  # $C00C65: TYA
    instr("AND", amImmediateM, 0x3),  # $C00C66: AND #$0003
    instrTo("BNE", amRelative8, "loc_C00C8D"),  # $C00C69: BNE +34
    instr("LDA", amDirectPage, 0x4),  # $C00C6B: LDA $04
    instr("LSR", amAccumulator),  # $C00C6D: LSR A
    instr("LSR", amAccumulator),  # $C00C6E: LSR A
    instr("LSR", amAccumulator),  # $C00C6F: LSR A
    instr("STA", amDirectPage, 0x2),  # $C00C70: STA $02
    instr("TYA", amImplied),  # $C00C72: TYA
    instr("AND", amImmediateM, 0xFFFC),  # $C00C73: AND #$FFFC
    instr("ASL", amAccumulator),  # $C00C76: ASL A
    instr("ASL", amAccumulator),  # $C00C77: ASL A
    instr("ASL", amAccumulator),  # $C00C78: ASL A
    instr("CLC", amImplied),  # $C00C79: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00C7A: ADC $02
    instr("TAX", amImplied),  # $C00C7C: TAX
    instr("SEP", amImmediate8, 0x20),  # $C00C7D: SEP #$20
    instr("LDA", amAbsoluteLongX, 0xD7A800),  # $C00C7F: LDA $D7A800,X
    instr("LSR", amAccumulator),  # $C00C83: LSR A
    instr("LSR", amAccumulator),  # $C00C84: LSR A
    instr("LSR", amAccumulator),  # $C00C85: LSR A
    instr("REP", amImmediate8, 0x20),  # $C00C86: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C00C88: AND #$00FF
    instr("STA", amDirectPage, 0x14),  # $C00C8B: STA $14
    label("loc_C00C8D"),
    instr("CPY", amImmediateX, 0x140),  # $C00C8D: CPY #$0140
    instrTo("BCS", amRelative8, "loc_C00CAD"),  # $C00C90: BCS +27
    instr("LDA", amAbsolute, 0x436E),  # $C00C92: LDA $436E
    instr("CMP", amDirectPage, 0x14),  # $C00C95: CMP $14
    instrTo("BNE", amRelative8, "loc_C00CAD"),  # $C00C97: BNE +20
    instr("TYX", amImplied),  # $C00C99: TYX
    instr("LDA", amDirectPage, 0x4),  # $C00C9A: LDA $04
    instr("JSR", amAbsolute, 0xA156),  # $C00C9C: JSR $A156
    instr("STA", amDirectPage, 0x18),  # $C00C9F: STA $18
    instr("LDA", amDirectPage, 0x10),  # $C00CA1: LDA $10
    instr("STA", amDirectPage, 0x2),  # $C00CA3: STA $02
    instr("ASL", amAccumulator),  # $C00CA5: ASL A
    instr("TAY", amImplied),  # $C00CA6: TAY
    instr("LDA", amDirectPage, 0x18),  # $C00CA7: LDA $18
    instr("STA", amDpIndirectY, 0x12),  # $C00CA9: STA ($12),Y
    instrTo("BRA", amRelative8, "loc_C00CB8"),  # $C00CAB: BRA +11
    label("loc_C00CAD"),
    instr("LDA", amDirectPage, 0x10),  # $C00CAD: LDA $10
    instr("STA", amDirectPage, 0x2),  # $C00CAF: STA $02
    instr("ASL", amAccumulator),  # $C00CB1: ASL A
    instr("TAY", amImplied),  # $C00CB2: TAY
    instr("LDA", amImmediateM, 0x0),  # $C00CB3: LDA #$0000
    instr("STA", amDpIndirectY, 0x12),  # $C00CB6: STA ($12),Y
    label("loc_C00CB8"),
    instr("LDA", amDirectPage, 0x2),  # $C00CB8: LDA $02
    instr("CLC", amImplied),  # $C00CBA: CLC
    instr("ADC", amImmediateM, 0x10),  # $C00CBB: ADC #$0010
    instr("AND", amImmediateM, 0xFF),  # $C00CBE: AND #$00FF
    instr("STA", amDirectPage, 0x2),  # $C00CC1: STA $02
    instr("STA", amDirectPage, 0x10),  # $C00CC3: STA $10
    instr("LDY", amDirectPage, 0x1A),  # $C00CC5: LDY $1A
    instr("INY", amImplied),  # $C00CC7: INY
    instr("STY", amDirectPage, 0x1A),  # $C00CC8: STY $1A
    instr("INC", amDirectPage, 0xE),  # $C00CCA: INC $0E
    label("loc_C00CCC"),
    instr("LDA", amDirectPage, 0xE),  # $C00CCC: LDA $0E
    instr("CMP", amImmediateM, 0x10),  # $C00CCE: CMP #$0010
    instrTo("BCC", amRelative8, "loc_C00C65"),  # $C00CD1: BCC -110
    instrTo("BRA", amRelative8, "loc_C00CF1"),  # $C00CD3: BRA +28
    label("loc_C00CD5"),
    instr("LDA", amImmediateM, 0x0),  # $C00CD5: LDA #$0000
    instr("STA", amDirectPage, 0x18),  # $C00CD8: STA $18
    instrTo("BRA", amRelative8, "loc_C00CEC"),  # $C00CDA: BRA +16
    label("loc_C00CDC"),
    instr("ASL", amAccumulator),  # $C00CDC: ASL A
    instr("ASL", amAccumulator),  # $C00CDD: ASL A
    instr("ASL", amAccumulator),  # $C00CDE: ASL A
    instr("ASL", amAccumulator),  # $C00CDF: ASL A
    instr("ASL", amAccumulator),  # $C00CE0: ASL A
    instr("TAY", amImplied),  # $C00CE1: TAY
    instr("LDA", amImmediateM, 0x0),  # $C00CE2: LDA #$0000
    instr("STA", amDpIndirectY, 0x12),  # $C00CE5: STA ($12),Y
    instr("LDA", amDirectPage, 0x18),  # $C00CE7: LDA $18
    instr("INC", amAccumulator),  # $C00CE9: INC A
    instr("STA", amDirectPage, 0x18),  # $C00CEA: STA $18
    label("loc_C00CEC"),
    instr("CMP", amImmediateM, 0x10),  # $C00CEC: CMP #$0010
    instrTo("BCC", amRelative8, "loc_C00CDC"),  # $C00CEF: BCC -21
    label("loc_C00CF1"),
    instr("PLD", amImplied),  # $C00CF1: PLD
    instr("RTS", amImplied),  # $C00CF2: RTS
    instr("REP", amImmediate8, 0x31),  # $C00CF3: REP #$31
    instr("PHD", amImplied),  # $C00CF5: PHD
    instr("PHA", amImplied),  # $C00CF6: PHA
    instr("TDC", amImplied),  # $C00CF7: TDC
    instr("ADC", amImmediateM, 0xFFEC),  # $C00CF8: ADC #$FFEC
    instr("TCD", amImplied),  # $C00CFB: TCD
    instr("PLA", amImplied),  # $C00CFC: PLA
    instr("TXA", amImplied),  # $C00CFD: TXA
    instr("STA", amDirectPage, 0x12),  # $C00CFE: STA $12
    instr("LSR", amAccumulator),  # $C00D00: LSR A
    instr("LSR", amAccumulator),  # $C00D01: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00D02: AND #$000F
    instr("ASL", amAccumulator),  # $C00D05: ASL A
    instr("ASL", amAccumulator),  # $C00D06: ASL A
    instr("ASL", amAccumulator),  # $C00D07: ASL A
    instr("ASL", amAccumulator),  # $C00D08: ASL A
    instr("ASL", amAccumulator),  # $C00D09: ASL A
    instr("CLC", amImplied),  # $C00D0A: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C00D0B: ADC #$F000
    instr("STA", amDirectPage, 0x2),  # $C00D0E: STA $02
    instr("LDA", amDirectPage, 0x12),  # $C00D10: LDA $12
    instr("AND", amImmediateM, 0x3F),  # $C00D12: AND #$003F
    instr("ASL", amAccumulator),  # $C00D15: ASL A
    instr("ASL", amAccumulator),  # $C00D16: ASL A
    instr("ASL", amAccumulator),  # $C00D17: ASL A
    instr("ASL", amAccumulator),  # $C00D18: ASL A
    instr("ASL", amAccumulator),  # $C00D19: ASL A
    instr("ASL", amAccumulator),  # $C00D1A: ASL A
    instr("CLC", amImplied),  # $C00D1B: CLC
    instr("ADC", amImmediateM, 0xE000),  # $C00D1C: ADC #$E000
    instr("TAX", amImplied),  # $C00D1F: TAX
    instr("STX", amDirectPage, 0x10),  # $C00D20: STX $10
    instr("LDA", amDirectPage, 0x12),  # $C00D22: LDA $12
    instr("AND", amImmediateM, 0x3),  # $C00D24: AND #$0003
    instr("ASL", amAccumulator),  # $C00D27: ASL A
    instr("ASL", amAccumulator),  # $C00D28: ASL A
    instr("STA", amDirectPage, 0x4),  # $C00D29: STA $04
    instr("LDY", amImmediateX, 0x0),  # $C00D2B: LDY #$0000
    instr("STY", amDirectPage, 0xE),  # $C00D2E: STY $0E
    instrTo("BRA", amRelative8, "loc_C00D77"),  # $C00D30: BRA +69
    label("loc_C00D32"),
    instr("LDX", amDirectPage, 0x2),  # $C00D32: LDX $02
    instr("LDA", amAbsoluteX, 0x0),  # $C00D34: LDA $0000,X
    instr("ASL", amAccumulator),  # $C00D37: ASL A
    instr("TAX", amImplied),  # $C00D38: TAX
    instr("LDA", amAbsoluteLongX, 0x7FF800),  # $C00D39: LDA $7FF800,X
    instr("STA", amDirectPage, 0x12),  # $C00D3D: STA $12
    instr("INC", amDirectPage, 0x2),  # $C00D3F: INC $02
    instr("INC", amDirectPage, 0x2),  # $C00D41: INC $02
    instr("LDA", amImmediateM, 0x0),  # $C00D43: LDA #$0000
    instr("STA", amDirectPage, 0x6),  # $C00D46: STA $06
    instr("LDA", amImmediateM, 0xD8),  # $C00D48: LDA #$00D8
    instr("STA", amDirectPage, 0x8),  # $C00D4B: STA $08
    instr("LDA", amDirectPage, 0x12),  # $C00D4D: LDA $12
    instr("CLC", amImplied),  # $C00D4F: CLC
    instr("ADC", amDirectPage, 0x4),  # $C00D50: ADC $04
    instr("CLC", amImplied),  # $C00D52: CLC
    instr("ADC", amDirectPage, 0x6),  # $C00D53: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C00D55: STA $06
    instr("STA", amDirectPage, 0xA),  # $C00D57: STA $0A
    instr("LDA", amDirectPage, 0x8),  # $C00D59: LDA $08
    instr("STA", amDirectPage, 0xC),  # $C00D5B: STA $0C
    instr("LDA", amDpIndirectLong, 0xA),  # $C00D5D: LDA [$0A]
    instr("LDX", amDirectPage, 0x10),  # $C00D5F: LDX $10
    instr("STA", amAbsoluteX, 0x0),  # $C00D61: STA $0000,X
    instr("LDY", amImmediateX, 0x2),  # $C00D64: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00D67: LDA [$06],Y
    instr("STA", amAbsoluteX, 0x2),  # $C00D69: STA $0002,X
    instr("INX", amImplied),  # $C00D6C: INX
    instr("INX", amImplied),  # $C00D6D: INX
    instr("INX", amImplied),  # $C00D6E: INX
    instr("INX", amImplied),  # $C00D6F: INX
    instr("STX", amDirectPage, 0x10),  # $C00D70: STX $10
    instr("LDY", amDirectPage, 0xE),  # $C00D72: LDY $0E
    instr("INY", amImplied),  # $C00D74: INY
    instr("STY", amDirectPage, 0xE),  # $C00D75: STY $0E
    label("loc_C00D77"),
    instr("CPY", amImmediateX, 0x10),  # $C00D77: CPY #$0010
    instrTo("BCC", amRelative8, "loc_C00D32"),  # $C00D7A: BCC -74
    instr("PLD", amImplied),  # $C00D7C: PLD
    instr("RTS", amImplied),  # $C00D7D: RTS
    instr("REP", amImmediate8, 0x31),  # $C00D7E: REP #$31
    instr("PHD", amImplied),  # $C00D80: PHD
    instr("PHA", amImplied),  # $C00D81: PHA
    instr("TDC", amImplied),  # $C00D82: TDC
    instr("ADC", amImmediateM, 0xFFEC),  # $C00D83: ADC #$FFEC
    instr("TCD", amImplied),  # $C00D86: TCD
    instr("PLA", amImplied),  # $C00D87: PLA
    instr("STA", amDirectPage, 0x12),  # $C00D88: STA $12
    instr("LSR", amAccumulator),  # $C00D8A: LSR A
    instr("LSR", amAccumulator),  # $C00D8B: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00D8C: AND #$000F
    instr("ASL", amAccumulator),  # $C00D8F: ASL A
    instr("CLC", amImplied),  # $C00D90: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C00D91: ADC #$F000
    instr("STA", amDirectPage, 0x2),  # $C00D94: STA $02
    instr("LDA", amDirectPage, 0x12),  # $C00D96: LDA $12
    instr("AND", amImmediateM, 0x3F),  # $C00D98: AND #$003F
    instr("CLC", amImplied),  # $C00D9B: CLC
    instr("ADC", amImmediateM, 0xE000),  # $C00D9C: ADC #$E000
    instr("TAX", amImplied),  # $C00D9F: TAX
    instr("STX", amDirectPage, 0x10),  # $C00DA0: STX $10
    instr("LDA", amDirectPage, 0x12),  # $C00DA2: LDA $12
    instr("AND", amImmediateM, 0x3),  # $C00DA4: AND #$0003
    instr("STA", amDirectPage, 0x4),  # $C00DA7: STA $04
    instr("LDY", amImmediateX, 0x0),  # $C00DA9: LDY #$0000
    instr("STY", amDirectPage, 0xE),  # $C00DAC: STY $0E
    instrTo("BRA", amRelative8, "loc_C00E0F"),  # $C00DAE: BRA +95
    label("loc_C00DB0"),
    instr("LDX", amDirectPage, 0x2),  # $C00DB0: LDX $02
    instr("LDA", amAbsoluteX, 0x0),  # $C00DB2: LDA $0000,X
    instr("ASL", amAccumulator),  # $C00DB5: ASL A
    instr("TAX", amImplied),  # $C00DB6: TAX
    instr("LDA", amAbsoluteLongX, 0x7FF800),  # $C00DB7: LDA $7FF800,X
    instr("STA", amDirectPage, 0x12),  # $C00DBB: STA $12
    instr("LDA", amDirectPage, 0x2),  # $C00DBD: LDA $02
    instr("CLC", amImplied),  # $C00DBF: CLC
    instr("ADC", amImmediateM, 0x20),  # $C00DC0: ADC #$0020
    instr("STA", amDirectPage, 0x2),  # $C00DC3: STA $02
    instr("LDA", amImmediateM, 0x0),  # $C00DC5: LDA #$0000
    instr("STA", amDirectPage, 0x6),  # $C00DC8: STA $06
    instr("LDA", amImmediateM, 0xD8),  # $C00DCA: LDA #$00D8
    instr("STA", amDirectPage, 0x8),  # $C00DCD: STA $08
    instr("LDA", amDirectPage, 0x12),  # $C00DCF: LDA $12
    instr("CLC", amImplied),  # $C00DD1: CLC
    instr("ADC", amDirectPage, 0x4),  # $C00DD2: ADC $04
    instr("CLC", amImplied),  # $C00DD4: CLC
    instr("ADC", amDirectPage, 0x6),  # $C00DD5: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C00DD7: STA $06
    instr("STA", amDirectPage, 0xA),  # $C00DD9: STA $0A
    instr("LDA", amDirectPage, 0x8),  # $C00DDB: LDA $08
    instr("STA", amDirectPage, 0xC),  # $C00DDD: STA $0C
    instr("SEP", amImmediate8, 0x20),  # $C00DDF: SEP #$20
    instr("LDA", amDpIndirectLong, 0xA),  # $C00DE1: LDA [$0A]
    instr("LDX", amDirectPage, 0x10),  # $C00DE3: LDX $10
    instr("STA", amAbsoluteX, 0x0),  # $C00DE5: STA $0000,X
    instr("LDY", amImmediateX, 0x4),  # $C00DE8: LDY #$0004
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00DEB: LDA [$06],Y
    instr("STA", amAbsoluteX, 0x40),  # $C00DED: STA $0040,X
    instr("LDY", amImmediateX, 0x8),  # $C00DF0: LDY #$0008
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00DF3: LDA [$06],Y
    instr("STA", amAbsoluteX, 0x80),  # $C00DF5: STA $0080,X
    instr("LDY", amImmediateX, 0xC),  # $C00DF8: LDY #$000C
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00DFB: LDA [$06],Y
    instr("STA", amAbsoluteX, 0xC0),  # $C00DFD: STA $00C0,X
    instr("REP", amImmediate8, 0x20),  # $C00E00: REP #$20
    instr("TXA", amImplied),  # $C00E02: TXA
    instr("CLC", amImplied),  # $C00E03: CLC
    instr("ADC", amImmediateM, 0x100),  # $C00E04: ADC #$0100
    instr("TAX", amImplied),  # $C00E07: TAX
    instr("STX", amDirectPage, 0x10),  # $C00E08: STX $10
    instr("LDY", amDirectPage, 0xE),  # $C00E0A: LDY $0E
    instr("INY", amImplied),  # $C00E0C: INY
    instr("STY", amDirectPage, 0xE),  # $C00E0D: STY $0E
    label("loc_C00E0F"),
    instr("CPY", amImmediateX, 0x10),  # $C00E0F: CPY #$0010
    instrTo("BCC", amRelative8, "loc_C00DB0"),  # $C00E12: BCC -100
    instr("PLD", amImplied),  # $C00E14: PLD
    instr("RTS", amImplied),  # $C00E15: RTS
    instr("REP", amImmediate8, 0x31),  # $C00E16: REP #$31
    instr("PHD", amImplied),  # $C00E18: PHD
    instr("PHA", amImplied),  # $C00E19: PHA
    instr("TDC", amImplied),  # $C00E1A: TDC
    instr("ADC", amImmediateM, 0xFFDE),  # $C00E1B: ADC #$FFDE
    instr("TCD", amImplied),  # $C00E1E: TCD
    instr("PLA", amImplied),  # $C00E1F: PLA
    instr("STX", amDirectPage, 0x4),  # $C00E20: STX $04
    instr("TAY", amImplied),  # $C00E22: TAY
    instr("STY", amDirectPage, 0x20),  # $C00E23: STY $20
    instr("LDA", amAbsolute, 0x436C),  # $C00E25: LDA $436C
    instrTo("BEQ", amRelative8, "loc_C00E31"),  # $C00E28: BEQ +7
    instr("LDX", amDirectPage, 0x4),  # $C00E2A: LDX $04
    instr("TYA", amImplied),  # $C00E2C: TYA
    instr("JSL", amAbsoluteLong, 0xEFDFC4),  # $C00E2D: JSL $EFDFC4
    label("loc_C00E31"),
    instr("LDA", amImmediateM, 0x100),  # $C00E31: LDA #$0100
    instr("JSL", amAbsoluteLong, 0xC086DE),  # $C00E34: JSL $C086DE
    instr("STA", amDirectPage, 0x1E),  # $C00E38: STA $1E
    instr("CLC", amImplied),  # $C00E3A: CLC
    instr("ADC", amImmediateM, 0x80),  # $C00E3B: ADC #$0080
    instr("STA", amDirectPage, 0x1C),  # $C00E3E: STA $1C
    instr("LDY", amDirectPage, 0x20),  # $C00E40: LDY $20
    instr("TYA", amImplied),  # $C00E42: TYA
    instr("DEC", amAccumulator),  # $C00E43: DEC A
    instr("STA", amDirectPage, 0x20),  # $C00E44: STA $20
    instr("LDA", amDirectPage, 0x4),  # $C00E46: LDA $04
    instr("LSR", amAccumulator),  # $C00E48: LSR A
    instr("LSR", amAccumulator),  # $C00E49: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00E4A: AND #$000F
    instr("ASL", amAccumulator),  # $C00E4D: ASL A
    instr("ASL", amAccumulator),  # $C00E4E: ASL A
    instr("ASL", amAccumulator),  # $C00E4F: ASL A
    instr("ASL", amAccumulator),  # $C00E50: ASL A
    instr("ASL", amAccumulator),  # $C00E51: ASL A
    instr("CLC", amImplied),  # $C00E52: CLC
    instr("ADC", amImmediateM, 0xF000),  # $C00E53: ADC #$F000
    instr("STA", amDirectPage, 0x1A),  # $C00E56: STA $1A
    instr("LDA", amDirectPage, 0x20),  # $C00E58: LDA $20
    instr("AND", amImmediateM, 0x3),  # $C00E5A: AND #$0003
    instr("PHA", amImplied),  # $C00E5D: PHA
    instr("LDA", amDirectPage, 0x4),  # $C00E5E: LDA $04
    instr("AND", amImmediateM, 0x3),  # $C00E60: AND #$0003
    instr("ASL", amAccumulator),  # $C00E63: ASL A
    instr("ASL", amAccumulator),  # $C00E64: ASL A
    instr("STA", amDirectPage, 0x2),  # $C00E65: STA $02
    instr("LDA", amDirectPage, 0x20),  # $C00E67: LDA $20
    instr("LSR", amAccumulator),  # $C00E69: LSR A
    instr("LSR", amAccumulator),  # $C00E6A: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00E6B: AND #$000F
    instr("ASL", amAccumulator),  # $C00E6E: ASL A
    instr("TAY", amImplied),  # $C00E6F: TAY
    instr("LDA", amDpIndirectY, 0x1A),  # $C00E70: LDA ($1A),Y
    instr("ASL", amAccumulator),  # $C00E72: ASL A
    instr("ASL", amAccumulator),  # $C00E73: ASL A
    instr("ASL", amAccumulator),  # $C00E74: ASL A
    instr("ASL", amAccumulator),  # $C00E75: ASL A
    instr("CLC", amImplied),  # $C00E76: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00E77: ADC $02
    instr("PLY", amImplied),  # $C00E79: PLY
    instr("STY", amDirectPage, 0x2),  # $C00E7A: STY $02
    instr("CLC", amImplied),  # $C00E7C: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00E7D: ADC $02
    instr("TAY", amImplied),  # $C00E7F: TAY
    instr("STY", amDirectPage, 0x18),  # $C00E80: STY $18
    instr("LDA", amDirectPage, 0x20),  # $C00E82: LDA $20
    instr("AND", amImmediateM, 0x3F),  # $C00E84: AND #$003F
    instr("TAX", amImplied),  # $C00E87: TAX
    instr("STX", amDirectPage, 0x16),  # $C00E88: STX $16
    instr("LDA", amImmediateM, 0x0),  # $C00E8A: LDA #$0000
    instr("STA", amDirectPage, 0x2),  # $C00E8D: STA $02
    instr("STA", amDirectPage, 0x14),  # $C00E8F: STA $14
    instr("BRA", amRelative8, 0x71),  # $C00E91: BRA +113
  ]
  result = assemble(nodes, 0xC00A30'u32,
                    FlagState(m8: false, x8: false, emulation: false))
