## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x00023F-0x00030E (SNES $C0023F), 208 bytes.

import
  ./[assembler, opcodes]

proc generateCode00023F*(): seq[uint8] =
  ## Assemble the region at file 0x00023F from disassembled source.
  let nodes = @[
    instr("REP", amImmediate8, 0x31),  # $C0023F: REP #$31
    instr("PHD", amImplied),  # $C00241: PHD
    instr("TDC", amImplied),  # $C00242: TDC
    instr("ADC", amImmediateM, 0xFFE8),  # $C00243: ADC #$FFE8
    instr("TCD", amImplied),  # $C00246: TCD
    instr("STZ", amAbsolute, 0x4474),  # $C00247: STZ $4474
    instr("LDX", amAbsolute, 0x2A0),  # $C0024A: LDX $02A0
    instrTo("BNE", amRelative8, "loc_C00252"),  # $C0024D: BNE +3
    instrTo("JMP", amAbsolute, "loc_C0030D"),  # $C0024F: JMP $030D
    label("loc_C00252"),
    instr("LDA", amImmediateM, 0xE4E1),  # $C00252: LDA #$E4E1
    instr("STA", amDirectPage, 0x6),  # $C00255: STA $06
    instr("LDA", amImmediateM, 0xDF),  # $C00257: LDA #$00DF
    instr("STA", amDirectPage, 0x8),  # $C0025A: STA $08
    instr("TXA", amImplied),  # $C0025C: TXA
    instr("DEC", amAccumulator),  # $C0025D: DEC A
    instr("ASL", amAccumulator),  # $C0025E: ASL A
    instr("ASL", amAccumulator),  # $C0025F: ASL A
    instr("CLC", amImplied),  # $C00260: CLC
    instr("ADC", amDirectPage, 0x6),  # $C00261: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C00263: STA $06
    instr("LDY", amImmediateX, 0x2),  # $C00265: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0x6),  # $C00268: LDA [$06],Y
    instr("TAY", amImplied),  # $C0026A: TAY
    instr("LDA", amDpIndirectLong, 0x6),  # $C0026B: LDA [$06]
    instr("STA", amDirectPage, 0xA),  # $C0026D: STA $0A
    instr("STY", amDirectPage, 0xC),  # $C0026F: STY $0C
    instr("SEP", amImmediate8, 0x20),  # $C00271: SEP #$20
    instr("LDY", amImmediateX, 0x4),  # $C00273: LDY #$0004
    instr("LDA", amDpIndirectLongY, 0xA),  # $C00276: LDA [$0A],Y
    instr("REP", amImmediate8, 0x20),  # $C00278: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C0027A: AND #$00FF
    instrTo("BNE", amRelative8, "loc_C00282"),  # $C0027D: BNE +3
    instrTo("JMP", amAbsolute, "loc_C0030D"),  # $C0027F: JMP $030D
    label("loc_C00282"),
    instr("LDA", amDirectPage, 0xA),  # $C00282: LDA $0A
    instr("STA", amDirectPage, 0x6),  # $C00284: STA $06
    instr("LDA", amDirectPage, 0xC),  # $C00286: LDA $0C
    instr("STA", amDirectPage, 0x8),  # $C00288: STA $08
    instr("LDY", amImmediateX, 0x2),  # $C0028A: LDY #$0002
    instr("LDA", amDpIndirectLongY, 0x6),  # $C0028D: LDA [$06],Y
    instr("TAY", amImplied),  # $C0028F: TAY
    instr("LDA", amDpIndirectLong, 0x6),  # $C00290: LDA [$06]
    instr("STA", amDirectPage, 0x6),  # $C00292: STA $06
    instr("STY", amDirectPage, 0x8),  # $C00294: STY $08
    instr("LDA", amDirectPage, 0x6),  # $C00296: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C00298: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C0029A: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C0029C: STA $10
    instr("LDA", amImmediateM, 0xB800),  # $C0029E: LDA #$B800
    instr("STA", amDirectPage, 0x12),  # $C002A1: STA $12
    instr("LDA", amImmediateM, 0x7E),  # $C002A3: LDA #$007E
    instr("STA", amDirectPage, 0x14),  # $C002A6: STA $14
    instr("JSL", amAbsoluteLong, 0xC41A9E),  # $C002A8: JSL $C41A9E
    instr("LDA", amImmediateM, 0x0),  # $C002AC: LDA #$0000
    instr("STA", amDirectPage, 0x16),  # $C002AF: STA $16
    instrTo("BRA", amRelative8, "loc_C002BD"),  # $C002B1: BRA +10
    label("loc_C002B3"),
    instr("ASL", amAccumulator),  # $C002B3: ASL A
    instr("TAX", amImplied),  # $C002B4: TAX
    instr("STZ", amAbsoluteX, 0x4460),  # $C002B5: STZ $4460,X
    instr("LDA", amDirectPage, 0x16),  # $C002B8: LDA $16
    instr("INC", amAccumulator),  # $C002BA: INC A
    instr("STA", amDirectPage, 0x16),  # $C002BB: STA $16
    label("loc_C002BD"),
    instr("CMP", amImmediateM, 0x9),  # $C002BD: CMP #$0009
    instrTo("BCC", amRelative8, "loc_C002B3"),  # $C002C0: BCC -15
    instr("LDA", amImmediateM, 0x5),  # $C002C2: LDA #$0005
    instr("LDX", amDirectPage, 0xA),  # $C002C5: LDX $0A
    instr("STX", amDirectPage, 0x6),  # $C002C7: STX $06
    instr("LDX", amDirectPage, 0xC),  # $C002C9: LDX $0C
    instr("STX", amDirectPage, 0x8),  # $C002CB: STX $08
    instr("CLC", amImplied),  # $C002CD: CLC
    instr("ADC", amDirectPage, 0x6),  # $C002CE: ADC $06
    instr("STA", amDirectPage, 0x6),  # $C002D0: STA $06
    instr("LDA", amImmediateM, 0x0),  # $C002D2: LDA #$0000
    instr("STA", amDirectPage, 0x16),  # $C002D5: STA $16
    instrTo("BRA", amRelative8, "loc_C002EA"),  # $C002D7: BRA +17
    label("loc_C002D9"),
    instr("ASL", amAccumulator),  # $C002D9: ASL A
    instr("TAX", amImplied),  # $C002DA: TAX
    instr("LDA", amDpIndirectLong, 0x6),  # $C002DB: LDA [$06]
    instr("AND", amImmediateM, 0xFF),  # $C002DD: AND #$00FF
    instr("STA", amAbsoluteX, 0x4460),  # $C002E0: STA $4460,X
    instr("INC", amDirectPage, 0x6),  # $C002E3: INC $06
    instr("LDA", amDirectPage, 0x16),  # $C002E5: LDA $16
    instr("INC", amAccumulator),  # $C002E7: INC A
    instr("STA", amDirectPage, 0x16),  # $C002E8: STA $16
    label("loc_C002EA"),
    instr("SEP", amImmediate8, 0x20),  # $C002EA: SEP #$20
    instr("LDY", amImmediateX, 0x4),  # $C002EC: LDY #$0004
    instr("LDA", amDpIndirectLongY, 0xA),  # $C002EF: LDA [$0A],Y
    instr("REP", amImmediate8, 0x20),  # $C002F1: REP #$20
    instr("AND", amImmediateM, 0xFF),  # $C002F3: AND #$00FF
    instr("STA", amDirectPage, 0x2),  # $C002F6: STA $02
    instr("LDA", amDirectPage, 0x16),  # $C002F8: LDA $16
    instr("CMP", amDirectPage, 0x2),  # $C002FA: CMP $02
    instrTo("BCC", amRelative8, "loc_C002D9"),  # $C002FC: BCC -37
    instr("LDA", amAbsolute, 0x4460),  # $C002FE: LDA $4460
    instr("STA", amAbsolute, 0x445C),  # $C00301: STA $445C
    instr("LDA", amImmediateM, 0x1),  # $C00304: LDA #$0001
    instr("STA", amAbsolute, 0x4474),  # $C00307: STA $4474
    instr("STA", amAbsolute, 0x445E),  # $C0030A: STA $445E
    label("loc_C0030D"),
    instr("PLD", amImplied),  # $C0030D: PLD
    instr("RTS", amImplied),  # $C0030E: RTS
  ]
  result = assemble(nodes, 0xC0023F'u32,
                    FlagState(m8: false, x8: false, emulation: false))
