## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x000EA5-0x000ED8 (SNES $C00EA5), 52 bytes.

import
  ./[assembler, opcodes]

proc generateCode000EA5*(): seq[uint8] =
  ## Assemble the region at file 0x000EA5 from disassembled source.
  let nodes = @[
    instr("LSR", amAccumulator),  # $C00EA5: LSR A
    instr("LSR", amAccumulator),  # $C00EA6: LSR A
    instr("AND", amImmediateM, 0xF),  # $C00EA7: AND #$000F
    instr("ASL", amAccumulator),  # $C00EAA: ASL A
    instr("TAY", amImplied),  # $C00EAB: TAY
    instr("LDA", amDpIndirectY, 0x1A),  # $C00EAC: LDA ($1A),Y
    instr("ASL", amAccumulator),  # $C00EAE: ASL A
    instr("ASL", amAccumulator),  # $C00EAF: ASL A
    instr("ASL", amAccumulator),  # $C00EB0: ASL A
    instr("ASL", amAccumulator),  # $C00EB1: ASL A
    instr("CLC", amImplied),  # $C00EB2: CLC
    instr("ADC", amDirectPage, 0x2),  # $C00EB3: ADC $02
    instr("TAY", amImplied),  # $C00EB5: TAY
    instr("STY", amDirectPage, 0x18),  # $C00EB6: STY $18
    instr("LDY", amDirectPage, 0x18),  # $C00EB8: LDY $18
    instr("TYA", amImplied),  # $C00EBA: TYA
    instr("ASL", amAccumulator),  # $C00EBB: ASL A
    instr("TAX", amImplied),  # $C00EBC: TAX
    instr("LDA", amAbsoluteLongX, 0x7F8000),  # $C00EBD: LDA $7F8000,X
    instr("STA", amDirectPage, 0x12),  # $C00EC1: STA $12
    instr("LDX", amDirectPage, 0x16),  # $C00EC3: LDX $16
    instr("TXA", amImplied),  # $C00EC5: TXA
    instr("ASL", amAccumulator),  # $C00EC6: ASL A
    instr("TAY", amImplied),  # $C00EC7: TAY
    instr("LDA", amDirectPage, 0x12),  # $C00EC8: LDA $12
    instr("STA", amDpIndirectY, 0x1E),  # $C00ECA: STA ($1E),Y
    instr("LDY", amDirectPage, 0x18),  # $C00ECC: LDY $18
    instr("INY", amImplied),  # $C00ECE: INY
    instr("STY", amDirectPage, 0x18),  # $C00ECF: STY $18
    instr("LDA", amDirectPage, 0x12),  # $C00ED1: LDA $12
    instr("AND", amImmediateM, 0x3FF),  # $C00ED3: AND #$03FF
    instr("CMP", amImmediateM, 0x180),  # $C00ED6: CMP #$0180
  ]
  result = assemble(nodes, 0xC00EA5'u32,
                    FlagState(m8: false, x8: false, emulation: false))
