## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x010000-0x010041 (SNES $C10000), 66 bytes.

import
  ./[assembler, opcodes]

proc generateInitCode*(): seq[uint8] =
  ## Assemble the region at file 0x010000 from disassembled source.
  let nodes = @[
    instr("JSR", amAbsolute, 0xA1D),  # $C10000: JSR $0A1D
    instr("RTL", amImplied),  # $C10003: RTL
    instr("REP", amImmediate8, 0x31),  # $C10004: REP #$31
    instr("PHD", amImplied),  # $C10006: PHD
    instr("TDC", amImplied),  # $C10007: TDC
    instr("ADC", amImmediateM, 0xFFEE),  # $C10008: ADC #$FFEE
    instr("TCD", amImplied),  # $C1000B: TCD
    instr("LDA", amDirectPage, 0x20),  # $C1000C: LDA $20
    instr("STA", amDirectPage, 0x6),  # $C1000E: STA $06
    instr("LDA", amDirectPage, 0x22),  # $C10010: LDA $22
    instr("STA", amDirectPage, 0x8),  # $C10012: STA $08
    instr("JSL", amAbsoluteLong, 0xC0943C),  # $C10014: JSL $C0943C
    instr("LDA", amDirectPage, 0x6),  # $C10018: LDA $06
    instr("STA", amDirectPage, 0xE),  # $C1001A: STA $0E
    instr("LDA", amDirectPage, 0x8),  # $C1001C: LDA $08
    instr("STA", amDirectPage, 0x10),  # $C1001E: STA $10
    instr("JSL", amAbsoluteLong, 0xC186B1),  # $C10020: JSL $C186B1
    label("loc_C10024"),
    instr("JSL", amAbsoluteLong, 0xC12DD5),  # $C10024: JSL $C12DD5
    instr("LDA", amAbsolute, 0xB4A8),  # $C10028: LDA $B4A8
    instr("CMP", amImmediateM, 0xFFFF),  # $C1002B: CMP #$FFFF
    instrTo("BNE", amRelative8, "loc_C10024"),  # $C1002E: BNE -12
    instr("JSL", amAbsoluteLong, 0xC09451),  # $C10030: JSL $C09451
    instr("PLD", amImplied),  # $C10034: PLD
    instr("RTL", amImplied),  # $C10035: RTL
    instr("REP", amImmediate8, 0x31),  # $C10036: REP #$31
    instr("STA", amAbsolute, 0x964D),  # $C10038: STA $964D
    instr("RTS", amImplied),  # $C1003B: RTS
    instr("REP", amImmediate8, 0x31),  # $C1003C: REP #$31
    instr("STZ", amAbsolute, 0x964D),  # $C1003E: STZ $964D
    instr("RTS", amImplied),  # $C10041: RTS
  ]
  result = assemble(nodes, 0xC10000'u32,
                    FlagState(m8: false, x8: false, emulation: false))
