## Generates Nim assembler-DSL module source from ROM disassembly.
## Library core used by tools/gen_source.nim (single region CLI) and
## tools/convert_all.nim (batch conversion of every traced region).
## Output is sourced from what the ROM actually says, never transcribed.

import
  std/[sets, strformat],
  ./[assembler, disasm, memmap, opcodes]

proc labelName(fileOffset: int): string =
  ## Label naming convention: the canonical SNES address.
  &"loc_{fileToSnes(fileOffset):06X}"

proc flagStateLiteral(flags: FlagState): string =
  ## Render a FlagState as Nim source.
  &"FlagState(m8: {flags.m8}, x8: {flags.x8}, emulation: {flags.emulation})"

proc generateModuleSource*(rom: openArray[uint8], offset: int, length: int,
                           procName: string, entryFlags: FlagState,
                           importPrefix: string = "./"): tuple[source: string, covered: int, instructions: int] =
  ## Generate a complete Nim module that assembles the given ROM region
  ## from disassembled mnemonics. importPrefix locates assembler/opcodes
  ## relative to where the module will live.
  let (instrs, covered) = decodeRange(rom, offset, length, entryFlags)

  var starts = initHashSet[int]()
  var fileOffsets: seq[int]
  var pos = offset
  for instr in instrs:
    starts.incl pos
    fileOffsets.add pos
    pos += instr.size

  var labels = initHashSet[int]()
  for i, instr in instrs:
    let target = branchTargetSnes(instr, fileToSnes(fileOffsets[i]))
    if target >= 0:
      let fileTarget = snesToFile(target.uint32)
      if fileTarget >= offset and fileTarget < offset + covered and
         fileTarget in starts:
        labels.incl fileTarget

  var src = ""
  src.add &"## Generated by sourcegen from the gold master ROM.\n"
  src.add &"## Region: file 0x{offset:06X}-0x{offset + length - 1:06X} (SNES ${fileToSnes(offset):06X}), {length} bytes.\n"
  src.add "\n"
  src.add "import\n"
  src.add &"  {importPrefix}[assembler, opcodes]\n"
  src.add "\n"
  src.add &"proc {procName}*(): seq[uint8] =\n"
  src.add &"  ## Assemble the region at file 0x{offset:06X} from disassembled source.\n"
  src.add "  var nodes: seq[AsmNode]\n"
  for i, instr in instrs:
    let fileOffset = fileOffsets[i]
    if fileOffset in labels:
      src.add &"  nodes.add label(\"{labelName(fileOffset)}\")\n"
    let info = OpcodeTable[instr.opcode]
    let target = branchTargetSnes(instr, fileToSnes(fileOffset))
    var line = ""
    var comment = &"  # ${fileToSnes(fileOffset):06X}: {formatInstruction(instr)}"
    if target >= 0:
      let fileTarget = snesToFile(target.uint32)
      # Long targets are only labeled when the original encoding used the
      # canonical bank; mirrored-bank encodings (e.g. JML $80xxxx) must stay
      # numeric or label resolution would re-encode them as $C0xxxx and
      # change the byte, despite being the same physical target.
      let labelSafe = info.mode != amAbsoluteLong or
        fileToSnes(fileTarget) == instr.operand
      if fileTarget >= 0 and fileTarget in labels and labelSafe and
         fileTarget >= offset and fileTarget < offset + covered:
        line = &"  nodes.add instrTo(\"{info.mnemonic}\", {info.mode}, \"{labelName(fileTarget)}\")"
      else:
        line = &"  nodes.add instr(\"{info.mnemonic}\", {info.mode}, 0x{instr.operand:X})"
        if fileTarget < 0:
          comment &= "  (target outside ROM)"
    elif instr.size == 1:
      line = &"  nodes.add instr(\"{info.mnemonic}\", {info.mode})"
    else:
      line = &"  nodes.add instr(\"{info.mnemonic}\", {info.mode}, 0x{instr.operand:X})"
    src.add line & comment & "\n"
  src.add &"  result = assemble(nodes, 0x{fileToSnes(offset):X}'u32,\n"
  src.add &"                    {flagStateLiteral(entryFlags)})\n"
  if covered < length:
    src.add "\n"
    src.add "  # Trailing bytes the linear decode could not cover as whole\n"
    src.add "  # instructions (region boundary cuts mid-instruction).\n"
    src.add "  # TODO: refine the region boundary when the code map improves.\n"
    var tail = "  result.add @["
    for i in (offset + covered)..<(offset + length):
      tail.add &"0x{rom[i]:02X}'u8, "
    tail = tail[0..^3] & "]\n"
    src.add tail

  result = (source: src, covered: covered, instructions: instrs.len)
