## Generated by tools/gen_source.nim from the gold master ROM.
## Region: file 0x00A156-0x00A1AD (SNES $C0A156), 88 bytes.

import
  ./[assembler, opcodes]

proc generateSubroutineA156*(): seq[uint8] =
  ## Assemble the region at file 0x00A156 from disassembled source.
  let nodes = @[
    instr("REP", amImmediate8, 0x20),  # $C0A156: REP #$20
    instr("PHD", amImplied),  # $C0A158: PHD
    instr("PHA", amImplied),  # $C0A159: PHA
    instr("TDC", amImplied),  # $C0A15A: TDC
    instr("SEC", amImplied),  # $C0A15B: SEC
    instr("SBC", amImmediateM, 0xA),  # $C0A15C: SBC #$000A
    instr("TCD", amImplied),  # $C0A15F: TCD
    instr("PLA", amImplied),  # $C0A160: PLA
    instr("STA", amDirectPage, 0x0),  # $C0A161: STA $00
    instr("STX", amDirectPage, 0x2),  # $C0A163: STX $02
    instr("ORA", amDirectPage, 0x2),  # $C0A165: ORA $02
    instrTo("BPL", amRelative8, "loc_C0A16E"),  # $C0A167: BPL +5
    instr("LDA", amImmediateM, 0xFFFF),  # $C0A169: LDA #$FFFF
    instr("PLD", amImplied),  # $C0A16C: PLD
    instr("RTS", amImplied),  # $C0A16D: RTS
    label("loc_C0A16E"),
    instr("LDA", amDirectPage, 0x0),  # $C0A16E: LDA $00
    instr("CMP", amAbsolute, 0x2888),  # $C0A170: CMP $2888
    instrTo("BNE", amRelative8, "loc_C0A17F"),  # $C0A173: BNE +10
    instr("CPX", amAbsolute, 0x288A),  # $C0A175: CPX $288A
    instrTo("BNE", amRelative8, "loc_C0A17F"),  # $C0A178: BNE +5
    instr("LDA", amAbsolute, 0x288C),  # $C0A17A: LDA $288C
    instr("PLD", amImplied),  # $C0A17D: PLD
    instr("RTS", amImplied),  # $C0A17E: RTS
    label("loc_C0A17F"),
    instr("STA", amAbsolute, 0x2888),  # $C0A17F: STA $2888
    instr("STX", amAbsolute, 0x288A),  # $C0A182: STX $288A
    instr("TXA", amImplied),  # $C0A185: TXA
    instr("LSR", amAccumulator),  # $C0A186: LSR A
    instr("LSR", amAccumulator),  # $C0A187: LSR A
    instr("LSR", amAccumulator),  # $C0A188: LSR A
    instr("XBA", amImplied),  # $C0A189: XBA
    instr("ORA", amDirectPage, 0x0),  # $C0A18A: ORA $00
    instr("TAY", amImplied),  # $C0A18C: TAY
    instr("LDA", amImmediateM, 0xD7),  # $C0A18D: LDA #$00D7
    instr("STA", amDirectPage, 0x6),  # $C0A190: STA $06
    instr("LDX", amImmediateX, 0x5000),  # $C0A192: LDX #$5000
    instr("LDA", amDirectPage, 0x2),  # $C0A195: LDA $02
    instr("AND", amImmediateM, 0x4),  # $C0A197: AND #$0004
    instrTo("BEQ", amRelative8, "loc_C0A19F"),  # $C0A19A: BEQ +3
    instr("LDX", amImmediateX, 0x8000),  # $C0A19C: LDX #$8000
    label("loc_C0A19F"),
    instr("STX", amDirectPage, 0x4),  # $C0A19F: STX $04
    instr("LDA", amDirectPage, 0x2),  # $C0A1A1: LDA $02
    instr("AND", amImmediateM, 0x7),  # $C0A1A3: AND #$0007
    instr("ASL", amAccumulator),  # $C0A1A6: ASL A
    instr("ASL", amAccumulator),  # $C0A1A7: ASL A
    instr("TAX", amImplied),  # $C0A1A8: TAX
    instr("LDA", amDpIndirectLongY, 0x4),  # $C0A1A9: LDA [$04],Y
    instr("JMP", amAbsIndirectX, 0xA1AE),  # $C0A1AB: JMP ($A1AE,X)
  ]
  result = assemble(nodes, 0xC0A156'u32,
                    FlagState(m8: false, x8: false, emulation: false))
