.PHONY: help build compare test clean regions boot screenshot intro title song vectors spc-vectors disasm play play-verbose gamepad-test sram serve frames lua-test llm-play llm-ai testrom script-dump gfx-roundtrip trace inspect audio-check

# bash + pipefail: the test loop pipes nim through sed, and without
# pipefail the pipeline's exit status is sed's (always 0), which turns
# every test failure into a false green.
SHELL := bash
.SHELLFLAGS := -o pipefail -c

ROM ?= bin/Earthbound (U) [!].smc
NIM_TEST_FLAGS ?= --hints:off --warnings:off

help:
	@echo "decompbound targets:"
	@echo "  make compare      - build the decomp ROM and compare against gold"
	@echo "  make test         - run the full test suite"
	@echo "  make boot         - trace the real ROM booting on the emulator"
	@echo "  make screenshot   - render the boot state to bin/screenshot.png"
	@echo "  make play         - windowed interactive player (arrows/ZXAS/Enter/RShift/Space/N/F12/+/ - /Esc)"
	@echo "  make intro        - screenshot the 'War Against Giygas' title card"
	@echo "  make title        - screenshot deep into the attract sequence"
	@echo "  make frames       - render reference frames to bin/frame_<N>.png"
	@echo "  make jukebox SONG=N - render EarthBound song N to bin/jukebox_songNNN.wav (7/8 songs play)"
	@echo "  make vectors      - full 65816 CPU vector sweep (needs bin/65816-vectors)"
	@echo "  make spc-vectors  - full SPC700 vector sweep (needs bin/spc700-vectors)"
	@echo "  make regions      - regenerate all code regions from the gold ROM"
	@echo "  make disasm OFF=0x8000 N=40 - disassemble at a file offset"
	@echo "  make lua-test     - build and run the Lua 5.3 embed smoke test (milestone 1)"

# nim.cfg is generated by nimby from the lock file; run `make nim.cfg`
# after changing nimby.lock.
nim.cfg: nimby.lock
	nimby sync -g nimby.lock

build: nim.cfg
	nim r src/decompbound.nim

compare: nim.cfg
	nim r src/decompbound.nim --compare

# --- Emulator ---------------------------------------------------------

boot: nim.cfg
	nim r -d:release src/tools/boot_trace.nim "$(ROM)" 2000000 25

screenshot: nim.cfg
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/screenshot.png 2500000
	@echo "wrote bin/screenshot.png (APE logo era)"

intro: nim.cfg
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/intro.png 16000000 noinput
	@echo "wrote bin/intro.png (the War Against Giygas title card)"

title: nim.cfg
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/title.png 64000000
	@echo "wrote bin/title.png (deep attract / file select era)"

frames: nim.cfg
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/frame_3629.png frame:3629 noinput
	@echo "wrote bin/frame_3629.png (EarthBound logo assembled, pre-gradient)"
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/frame_4200.png frame:4200 noinput
	@echo "wrote bin/frame_4200.png (logo with glow)"
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/frame_8000.png frame:8000 noinput
	@echo "wrote bin/frame_8000.png (attract-mode world exploration with credits)"
	nim r -d:release src/tools/screenshot.nim "$(ROM)" bin/frame_10000.png frame:10000 noinput
	@echo "wrote bin/frame_10000.png (attract-mode world exploration with credits)"

play: nim.cfg
	@mkdir -p bin
	@printf '%s  commit %s%s  ROM=%s\n' "$$(date '+%Y-%m-%d %H:%M:%S')" "$$(git rev-parse --short HEAD 2>/dev/null || echo unknown)" "$$(git diff --quiet HEAD 2>/dev/null || echo ' +dirty')" "$(ROM)" | tee -a bin/play_sessions.log
	nim r -d:release src/tools/play.nim "$(ROM)"
	@echo "player exited"

# Same as play, but prints which paddy gamepad buttons/axes fire — use this to
# report how a specific controller maps its face buttons + d-pad.
play-verbose: nim.cfg
	nim r -d:release src/tools/play.nim --verbose "$(ROM)"
	@echo "player exited"

# Standalone USB controller tester: shows how a pad reports its buttons/d-pad
# and which SNES button each maps to. No window/ROM needed. Ctrl+C to quit.
gamepad-test: nim.cfg
	nim r -d:release src/tools/gamepad_test.nim

# Inspect the EarthBound battery save (SRAM). `make sram` dumps mapped fields;
# `make sram ARGS="--find 20"` locates a value so we can map more of the format.
sram: nim.cfg
	nim r -d:release src/tools/sram_info.nim $(ARGS)

# Serve docs/ locally (HTML docs + diagrams) via Mummy. Open http://localhost:8080/
# Override the port with: make serve PORT=9000
PORT ?= 8080
serve: nim.cfg
	nim r -d:release src/tools/serve.nim $(PORT)

# Jukebox: render an EarthBound song to a WAV via the standalone SPC player.
# Pick a track with SONG=N (default 1); output -> bin/jukebox_songNNN.wav.
# Extra flags via ARGS, e.g.: make jukebox SONG=15 ARGS="--seconds 10"
SONG ?= 1
jukebox song: nim.cfg
	@mkdir -p bin
	nim r -d:release src/tools/sound_explore.nim --song $(SONG) $(ARGS) "$(ROM)"

# --- Verification -----------------------------------------------------

vectors: nim.cfg
	nim r -d:release src/tools/run_vectors.nim 0

spc-vectors: nim.cfg
	nim r -d:release src/tools/run_spc_vectors.nim 0

# --- Reverse engineering ----------------------------------------------

regions: nim.cfg
	nim r src/tools/convert_all.nim "$(ROM)"

OFF ?= 0x8000
N ?= 40
disasm: nim.cfg
	nim r src/tools/disasm.nim "$(ROM)" $(OFF) $(N)

lua-test: nim.cfg
	nim r src/tools/lua_test.nim

llm-play: nim.cfg
	@mkdir -p bin
	nim r src/tools/llm_play.nim --frames 240 "$(ROM)" examples/policy_demo.lua

# LLM plays EarthBound: an azem-hosted model (qwen3.6-35b-a3b) writes the Lua
# policy live. Drops frames to bin/ (--png-every) so you can watch its progress.
llm-ai: nim.cfg
	@mkdir -p bin
	nim r src/tools/llm_ai.nim -- --no-mock --frames 600 --png-every 30 "$(ROM)"

# Run a SNES test ROM through the accuracy harness (PASS/FAIL/UNKNOWN + a frame
# dump). e.g. make testrom ROM=bin/testroms/blargg/test_speed.smc FRAMES=400
testrom: nim.cfg
	nim r src/tools/testrom.nim -- "$(ROM)" $(FRAMES)

# Decode + dump a dialogue block from the ROM to stdout (never committed).
# e.g. make script-dump OFF=0x63040
script-dump: nim.cfg
	nim r src/tools/script_dump.nim "$(ROM)" $(OFF)

# Verify the graphics compression codec round-trips byte-exact against the ROM.
gfx-roundtrip: nim.cfg
	nim r src/tools/gfx_roundtrip.nim "$(ROM)"

# Trace emulator state changes to bin/trace.log — the decomp instrument. Pass
# options via ARGS, e.g. make trace ARGS="--frames 240 --watch 0x0020-0x0120"
# (add --load-srm to boot your .srm and reach a real game state).
trace: nim.cfg
	@mkdir -p bin
	nim r src/tools/trace_tool.nim -- $(ARGS) "$(ROM)"

# Inspect a save-state slot: dump PPU/HDMA config + the HDMA table + per-line TM/TS
# bands, and render it to bin/state_inspect.png. Diagnoses battle/render bugs from a
# Ctrl+1 save-state. e.g. make inspect SLOT=1
inspect: nim.cfg
	@mkdir -p bin
	nim r src/tools/state_inspect.nim -- "$(ROM)" $(SLOT) bin/state_inspect.png

# Audio regression gate for S-DSP (silence/halving). Headless collect + peak/RMS
# assert + WAV capture. Run on title/intro or --load-state for specific SFX.
audio-check: nim.cfg
	@mkdir -p bin
	nim r src/tools/audio_check.nim --frames 1400 "$(ROM)"

test: nim.cfg
	@files=$$(ls tests/test_*.nim 2>/dev/null); \
	if [ -z "$$files" ]; then \
		echo "No unit tests found in tests/test_*.nim"; \
		exit 0; \
	fi; \
	fail=0; \
	pids=""; \
	for f in $$files; do \
		( nim r $(NIM_TEST_FLAGS) "$$f" 2>&1 | sed "s|^|[$$f] |" ) & \
		pids="$$pids $$!"; \
	done; \
	for pid in $$pids; do \
		wait $$pid || fail=1; \
	done; \
	exit $$fail

clean:
	rm -f bin/Decompbound.smc bin/screenshot.png bin/intro.png bin/title.png bin/song.wav bin/frame_*.png
