.PHONY: build test compare clean

# bash + pipefail: the test loop pipes nim through sed, and without
# pipefail the pipeline's exit status is sed's (always 0), which turns
# every test failure into a false green.
SHELL := bash
.SHELLFLAGS := -o pipefail -c

# nim.cfg is generated by nimby from the lock file; run `make nim.cfg`
# after changing nimby.lock.
nim.cfg: nimby.lock
	nimby sync -g nimby.lock

build: nim.cfg
	nim r src/decompbound.nim

compare: nim.cfg
	nim r src/decompbound.nim --compare

NIM_TEST_FLAGS ?= --hints:off --warnings:off

test: nim.cfg
	@files=$$(ls tests/test_*.nim 2>/dev/null); \
	if [ -z "$$files" ]; then \
		echo "No unit tests found in tests/test_*.nim"; \
		exit 0; \
	fi; \
	fail=0; \
	pids=""; \
	for f in $$files; do \
		( nim r $(NIM_TEST_FLAGS) "$$f" 2>&1 | sed "s|^|[$$f] |" ) & \
		pids="$$pids $$!"; \
	done; \
	for pid in $$pids; do \
		wait $$pid || fail=1; \
	done; \
	exit $$fail

clean:
	rm -f bin/Decompbound.smc
