.PHONY: help build compare test clean regions boot screenshot intro title song vectors spc-vectors disasm

# bash + pipefail: the test loop pipes nim through sed, and without
# pipefail the pipeline's exit status is sed's (always 0), which turns
# every test failure into a false green.
SHELL := bash
.SHELLFLAGS := -o pipefail -c

ROM ?= bin/Earthbound (U) [!].smc
NIM_TEST_FLAGS ?= --hints:off --warnings:off

help:
	@echo "decompbound targets:"
	@echo "  make compare      - build the decomp ROM and compare against gold"
	@echo "  make test         - run the full test suite"
	@echo "  make boot         - trace the real ROM booting on the emulator"
	@echo "  make screenshot   - render the boot state to bin/screenshot.png"
	@echo "  make intro        - screenshot the 'War Against Giygas' title card"
	@echo "  make title        - screenshot deep into the attract sequence"
	@echo "  make song         - (WIP) render captured music to bin/song.wav"
	@echo "  make vectors      - full 65816 CPU vector sweep (needs bin/65816-vectors)"
	@echo "  make spc-vectors  - full SPC700 vector sweep (needs bin/spc700-vectors)"
	@echo "  make regions      - regenerate all code regions from the gold ROM"
	@echo "  make disasm OFF=0x8000 N=40 - disassemble at a file offset"

# nim.cfg is generated by nimby from the lock file; run `make nim.cfg`
# after changing nimby.lock.
nim.cfg: nimby.lock
	nimby sync -g nimby.lock

build: nim.cfg
	nim r src/decompbound.nim

compare: nim.cfg
	nim r src/decompbound.nim --compare

# --- Emulator ---------------------------------------------------------

boot: nim.cfg
	nim r src/tools/boot_trace.nim "$(ROM)" 2000000 25

screenshot: nim.cfg
	nim r src/tools/screenshot.nim "$(ROM)" bin/screenshot.png 2500000
	@echo "wrote bin/screenshot.png (APE logo era)"

intro: nim.cfg
	nim r src/tools/screenshot.nim "$(ROM)" bin/intro.png 16000000 noinput
	@echo "wrote bin/intro.png (the War Against Giygas title card)"

title: nim.cfg
	nim r src/tools/screenshot.nim "$(ROM)" bin/title.png 64000000
	@echo "wrote bin/title.png (deep attract / file select era)"

song: nim.cfg
	nim r src/tools/render_song.nim "$(ROM)" bin/song.wav 30
	@echo "wrote bin/song.wav (WIP: upload capture bug means silence for now)"

# --- Verification -----------------------------------------------------

vectors: nim.cfg
	nim r -d:release src/tools/run_vectors.nim 0

spc-vectors: nim.cfg
	nim r -d:release src/tools/run_spc_vectors.nim 0

# --- Reverse engineering ----------------------------------------------

regions: nim.cfg
	nim r src/tools/convert_all.nim "$(ROM)"

OFF ?= 0x8000
N ?= 40
disasm: nim.cfg
	nim r src/tools/disasm.nim "$(ROM)" $(OFF) $(N)

test: nim.cfg
	@files=$$(ls tests/test_*.nim 2>/dev/null); \
	if [ -z "$$files" ]; then \
		echo "No unit tests found in tests/test_*.nim"; \
		exit 0; \
	fi; \
	fail=0; \
	pids=""; \
	for f in $$files; do \
		( nim r $(NIM_TEST_FLAGS) "$$f" 2>&1 | sed "s|^|[$$f] |" ) & \
		pids="$$pids $$!"; \
	done; \
	for pid in $$pids; do \
		wait $$pid || fail=1; \
	done; \
	exit $$fail

clean:
	rm -f bin/Decompbound.smc bin/screenshot.png bin/intro.png bin/title.png bin/song.wav
