## Batch conversion: trace the gold ROM from its interrupt vectors and
## generate an assembler-DSL module for every discovered code region,
## plus a registry module the ROM builder consumes.
## Usage: nim r src/tools/convert_all.nim <rom_file>
##
## Regions get the entry flag state the tracer actually observed at their
## start, so immediate widths reflect traced reality rather than guesses.

import
  std/[algorithm, os, strformat, strutils, tables],
  ../decompbound/[adopted, assembler, disasm, memmap, opcodes, sourcegen]

const
  OutputDir = "src/decompbound/generated"
  EmulationVectors = [0xFFF4, 0xFFF8, 0xFFFA, 0xFFFC, 0xFFFE]
  NativeVectors = [0xFFE4, 0xFFE6, 0xFFE8, 0xFFEA, 0xFFEE]
  HeaderRegion = (start: 0xFFB0, last: 0xFFFF)
  # Ground-truth code entry points the emulator observed the CPU fetching from
  # (regenerate with tools/probe_pc_coverage.nim). Static tracing stops at every
  # computed/indirect jump; these seeds carry it past the frontier with code we
  # know is real because it actually executed. Addresses only — safe to commit.
  ObservedEntriesFile = "src/decompbound/observed_entries.txt"

proc loadObservedEntries(rom: seq[uint8]): seq[int] =
  ## Parse the observed-entry list (hex SNES addresses) into file offsets.
  if not fileExists(ObservedEntriesFile): return
  for rawLine in readFile(ObservedEntriesFile).splitLines():
    let line = rawLine.strip()
    if line.len == 0 or line.startsWith("#"): continue
    let off = snesToFile(parseHexInt(line).uint32)
    if off >= 0 and off < rom.len:
      result.add off

proc readRomFile(filepath: string): seq[uint8] =
  ## Read ROM file and return bytes, stripping a 512-byte copier header.
  let data = readFile(filepath)
  var start = 0
  if data.len mod 1024 == 512:
    start = 512
  result = newSeq[uint8](data.len - start)
  for i in 0..<result.len:
    result[i] = data[start + i].uint8

proc readVector(data: seq[uint8], fileOffset: int): int =
  ## Read a 16-bit interrupt vector and map it to a file offset.
  let vec = data[fileOffset].int or (data[fileOffset + 1].int shl 8)
  result = snesToFile(vec.uint32)

proc main() =
  if paramCount() < 1:
    echo "Usage: nim r src/tools/convert_all.nim <rom_file>"
    quit(1)

  let rom = readRomFile(paramStr(1))

  var entryPoints: seq[int]
  for vecOffset in EmulationVectors:
    let target = readVector(rom, vecOffset)
    if target >= 0 and target < rom.len:
      entryPoints.add target
  for vecOffset in NativeVectors:
    let target = readVector(rom, vecOffset)
    if target >= 0 and target < rom.len:
      entryPoints.add target

  let observed = loadObservedEntries(rom)
  entryPoints.add observed
  if observed.len > 0:
    stderr.writeLine &"Seeding {observed.len} emulator-observed entry points."

  stderr.writeLine "Tracing control flow from vectors..."
  let analysis = analyzeControlFlow(rom, entryPoints, @[HeaderRegion])

  # Group contiguous code bytes into regions.
  var regions: seq[tuple[start: int, length: int]]
  var i = 0
  while i < analysis.byteTypes.len:
    if analysis.byteTypes[i] == Code:
      let start = i
      while i < analysis.byteTypes.len and analysis.byteTypes[i] == Code:
        inc i
      regions.add (start: start, length: i - start)
    else:
      inc i

  removeDir(OutputDir)
  createDir(OutputDir)

  var moduleNames: seq[string]
  var regionEntries: seq[string]
  var totalBytes = 0
  var totalInstructions = 0

  # Pack regions into one module per ROM bank (file offset >> 16) rather than
  # one file per region. Emulator-observed seeding produces thousands of small
  # regions; a file each explodes `make compare`/`make test` compile time, so
  # group them — same regions, same bytes, far fewer translation units.
  var byBank: OrderedTable[int, seq[tuple[start: int, length: int]]]
  var skippedAdopted = 0
  for region in regions:
    if isAdoptedOffset(region.start):
      # Goal 1.5: curated modules own these ranges; do not regenerate.
      skippedAdopted += 1
      continue
    byBank.mgetOrPut(region.start shr 16, @[]).add region

  for bank, bankRegions in byBank:
    let name = &"code_bank{bank:02X}"
    var moduleSrc = ""
    moduleSrc.add "## Generated by tools/convert_all.nim from the gold master ROM. Do not edit.\n"
    moduleSrc.add &"## Bank 0x{bank:02X}: {bankRegions.len} region(s).\n"
    moduleSrc.add "\n"
    moduleSrc.add "import\n"
    moduleSrc.add "  ../[assembler, opcodes]\n"
    moduleSrc.add "\n"
    for region in bankRegions:
      let procName = &"generateCode{region.start:06X}"
      let entryFlags = analysis.entryFlagStates.getOrDefault(
        region.start, FlagState(m8: false, x8: false, emulation: false))
      let (source, covered, instructions) = generateRegionProc(
        rom, region.start, region.length, procName, entryFlags)
      moduleSrc.add source
      moduleSrc.add "\n"
      regionEntries.add &"  result.add (offset: 0x{region.start:06X}, data: {procName}())"
      totalBytes += region.length
      totalInstructions += instructions
      discard covered
    writeFile(OutputDir / name & ".nim", moduleSrc)
    moduleNames.add name

  # Registry module importing every generated bank module.
  var registry = ""
  registry.add "## Generated by tools/convert_all.nim. Do not edit by hand.\n"
  registry.add &"## {moduleNames.len} code regions, {totalBytes} bytes, {totalInstructions} instructions.\n"
  registry.add "\n"
  registry.add "import\n"
  for i, name in moduleNames:
    let sep = if i < moduleNames.len - 1: "," else: ""
    registry.add &"  ./{name}{sep}\n"
  registry.add "\n"
  registry.add "proc allCodeRegions*(): seq[tuple[offset: int, data: seq[uint8]]] =\n"
  registry.add "  ## Every traced code region, assembled from mnemonics.\n"
  for entry in regionEntries:
    registry.add entry & "\n"
  writeFile(OutputDir / "registry.nim", registry)

  # The frontier: every computed/indirect jump static tracing stops at.
  # These are the doors the code map cannot open without the Goal 2
  # emulator (or manual jump-table analysis).
  var frontier = analysis.frontier
  frontier.sort(proc(a, b: FrontierSite): int = cmp(a.fileOffset, b.fileOffset))
  var report = ""
  report.add "# Static tracing frontier\n"
  report.add "\n"
  report.add "Generated by tools/convert_all.nim. Do not edit by hand.\n"
  report.add "\n"
  report.add &"{frontier.len} computed/indirect jump sites where static control\n"
  report.add "flow tracing stops. Each is a TODO: resolve the jump table or\n"
  report.add "observe the targets at runtime (Goal 2 emulator), then re-trace.\n"
  report.add "\n"
  for site in frontier:
    let snesAddr = fileToSnes(site.fileOffset)
    report.add &"- `${snesAddr:06X}` (file 0x{site.fileOffset:06X}): `{formatInstruction(site.instr)}`\n"
  writeFile(OutputDir / "frontier.md", report)

  stderr.writeLine &"Generated {moduleNames.len} region modules: {totalBytes} bytes, {totalInstructions} instructions."
  if skippedAdopted > 0:
    stderr.writeLine &"Skipped {skippedAdopted} adopted region(s) (see decompbound/adopted.nim)."
  stderr.writeLine &"Frontier: {frontier.len} computed-jump sites recorded in {OutputDir}/frontier.md."

when isMainModule:
  main()
