## Batch conversion: trace the gold ROM from its interrupt vectors and
## generate an assembler-DSL module for every discovered code region,
## plus a registry module the ROM builder consumes.
## Usage: nim r src/tools/convert_all.nim <rom_file>
##
## Regions get the entry flag state the tracer actually observed at their
## start, so immediate widths reflect traced reality rather than guesses.

import
  std/[os, strformat, tables],
  ../decompbound/[disasm, memmap, opcodes, sourcegen]

const
  OutputDir = "src/decompbound/generated"
  EmulationVectors = [0xFFF4, 0xFFF8, 0xFFFA, 0xFFFC, 0xFFFE]
  NativeVectors = [0xFFE4, 0xFFE6, 0xFFE8, 0xFFEA, 0xFFEE]
  HeaderRegion = (start: 0xFFB0, last: 0xFFFF)

proc readRomFile(filepath: string): seq[uint8] =
  ## Read ROM file and return bytes, stripping a 512-byte copier header.
  let data = readFile(filepath)
  var start = 0
  if data.len mod 1024 == 512:
    start = 512
  result = newSeq[uint8](data.len - start)
  for i in 0..<result.len:
    result[i] = data[start + i].uint8

proc readVector(data: seq[uint8], fileOffset: int): int =
  ## Read a 16-bit interrupt vector and map it to a file offset.
  let vec = data[fileOffset].int or (data[fileOffset + 1].int shl 8)
  result = snesToFile(vec.uint32)

proc main() =
  if paramCount() < 1:
    echo "Usage: nim r src/tools/convert_all.nim <rom_file>"
    quit(1)

  let rom = readRomFile(paramStr(1))

  var entryPoints: seq[int]
  for vecOffset in EmulationVectors:
    let target = readVector(rom, vecOffset)
    if target >= 0 and target < rom.len:
      entryPoints.add target
  for vecOffset in NativeVectors:
    let target = readVector(rom, vecOffset)
    if target >= 0 and target < rom.len:
      entryPoints.add target

  stderr.writeLine "Tracing control flow from vectors..."
  let analysis = analyzeControlFlow(rom, entryPoints, @[HeaderRegion])

  # Group contiguous code bytes into regions.
  var regions: seq[tuple[start: int, length: int]]
  var i = 0
  while i < analysis.byteTypes.len:
    if analysis.byteTypes[i] == Code:
      let start = i
      while i < analysis.byteTypes.len and analysis.byteTypes[i] == Code:
        inc i
      regions.add (start: start, length: i - start)
    else:
      inc i

  removeDir(OutputDir)
  createDir(OutputDir)

  var moduleNames: seq[string]
  var regionEntries: seq[string]
  var totalBytes = 0
  var totalInstructions = 0

  for region in regions:
    let name = &"code_{region.start:06X}"
    let procName = &"generateCode{region.start:06X}"
    let entryFlags = analysis.entryFlagStates.getOrDefault(
      region.start, FlagState(m8: false, x8: false, emulation: false))
    let (source, covered, instructions) = generateModuleSource(
      rom, region.start, region.length, procName, entryFlags,
      importPrefix = "../")
    writeFile(OutputDir / name & ".nim", source)
    moduleNames.add name
    regionEntries.add &"  result.add (offset: 0x{region.start:06X}, data: {procName}())"
    totalBytes += region.length
    totalInstructions += instructions
    discard covered

  # Registry module importing every generated region.
  var registry = ""
  registry.add "## Generated by tools/convert_all.nim. Do not edit by hand.\n"
  registry.add &"## {regions.len} code regions, {totalBytes} bytes, {totalInstructions} instructions.\n"
  registry.add "\n"
  registry.add "import\n"
  for i, name in moduleNames:
    let sep = if i < moduleNames.len - 1: "," else: ""
    registry.add &"  ./{name}{sep}\n"
  registry.add "\n"
  registry.add "proc allCodeRegions*(): seq[tuple[offset: int, data: seq[uint8]]] =\n"
  registry.add "  ## Every traced code region, assembled from mnemonics.\n"
  for entry in regionEntries:
    registry.add entry & "\n"
  writeFile(OutputDir / "registry.nim", registry)

  stderr.writeLine &"Generated {regions.len} region modules: {totalBytes} bytes, {totalInstructions} instructions."

when isMainModule:
  main()
