## Generates Nim assembler-DSL source from gold ROM disassembly.
## This is how byte-literal regions get converted to mnemonics: the output
## is sourced from what the ROM actually says, not from human transcription.
## Usage: nim r src/tools/gen_source.nim <rom> <offset> <length> <procName> [--emu|--m8|--x8]

import
  std/[os, sets, strformat, strutils],
  ../decompbound/[assembler, disasm, memmap, opcodes]

proc readRomFile(filepath: string): seq[uint8] =
  ## Read ROM file and return bytes, stripping a 512-byte copier header.
  let data = readFile(filepath)
  var start = 0
  if data.len mod 1024 == 512:
    start = 512
  result = newSeq[uint8](data.len - start)
  for i in 0..<result.len:
    result[i] = data[start + i].uint8

proc labelName(fileOffset: int): string =
  ## Label naming convention: the canonical SNES address.
  &"loc_{fileToSnes(fileOffset):06X}"

proc flagStateLiteral(flags: FlagState): string =
  ## Render a FlagState as Nim source.
  &"FlagState(m8: {flags.m8}, x8: {flags.x8}, emulation: {flags.emulation})"

proc main() =
  var positional: seq[string]
  var entryFlags = FlagState(m8: false, x8: false, emulation: false)
  for i in 1..paramCount():
    let arg = paramStr(i)
    case arg:
    of "--emu":
      entryFlags = initFlagState()
    of "--m8":
      entryFlags.m8 = true
    of "--x8":
      entryFlags.x8 = true
    else:
      positional.add arg

  if positional.len < 4:
    echo "Usage: nim r src/tools/gen_source.nim <rom> <offset> <length> <procName> [--emu|--m8|--x8]"
    quit(1)

  let romFile = positional[0]
  var offsetStr = positional[1]
  if offsetStr.startsWith("0x"):
    offsetStr = offsetStr[2..^1]
  let offset = parseHexInt(offsetStr)
  let length = parseInt(positional[2])
  let procName = positional[3]

  let rom = readRomFile(romFile)
  let (instrs, covered) = decodeRange(rom, offset, length, entryFlags)

  # Instruction start offsets, for label placement validity.
  var starts = initHashSet[int]()
  var fileOffsets: seq[int]
  var pos = offset
  for instr in instrs:
    starts.incl pos
    fileOffsets.add pos
    pos += instr.size

  # In-region branch targets that land on instruction boundaries get labels.
  var labels = initHashSet[int]()
  for i, instr in instrs:
    let target = branchTargetSnes(instr, fileToSnes(fileOffsets[i]))
    if target >= 0:
      let fileTarget = snesToFile(target.uint32)
      if fileTarget >= offset and fileTarget < offset + covered and
         fileTarget in starts:
        labels.incl fileTarget

  echo &"## Generated by tools/gen_source.nim from the gold master ROM."
  echo &"## Region: file 0x{offset:06X}-0x{offset + length - 1:06X} (SNES ${fileToSnes(offset):06X}), {length} bytes."
  echo ""
  echo "import"
  echo "  ./[assembler, opcodes]"
  echo ""
  echo &"proc {procName}*(): seq[uint8] ="
  echo &"  ## Assemble the region at file 0x{offset:06X} from disassembled source."
  echo "  let nodes = @["
  for i, instr in instrs:
    let fileOffset = fileOffsets[i]
    if fileOffset in labels:
      echo &"    label(\"{labelName(fileOffset)}\"),"
    let info = OpcodeTable[instr.opcode]
    let target = branchTargetSnes(instr, fileToSnes(fileOffset))
    var line = ""
    var comment = &"  # ${fileToSnes(fileOffset):06X}: {formatInstruction(instr)}"
    if target >= 0:
      let fileTarget = snesToFile(target.uint32)
      if fileTarget >= 0 and fileTarget in labels and
         fileTarget >= offset and fileTarget < offset + covered:
        line = &"    instrTo(\"{info.mnemonic}\", {info.mode}, \"{labelName(fileTarget)}\"),"
      else:
        line = &"    instr(\"{info.mnemonic}\", {info.mode}, 0x{instr.operand:X}),"
        if target >= 0 and snesToFile(target.uint32) < 0:
          comment &= "  (target outside ROM)"
    elif instr.size == 1:
      line = &"    instr(\"{info.mnemonic}\", {info.mode}),"
    else:
      line = &"    instr(\"{info.mnemonic}\", {info.mode}, 0x{instr.operand:X}),"
    echo line & comment
  echo "  ]"
  echo &"  result = assemble(nodes, 0x{fileToSnes(offset):X}'u32,"
  echo &"                    {flagStateLiteral(entryFlags)})"
  if covered < length:
    echo ""
    echo &"  # Trailing bytes the linear decode could not cover as whole"
    echo &"  # instructions (region boundary is arbitrary). Declared as data."
    echo &"  # TODO: refine the region boundary when the code map improves."
    var tail = "  result.add @["
    for i in (offset + covered)..<(offset + length):
      tail &= &"0x{rom[i]:02X}'u8, "
    tail = tail[0..^3] & "]"
    echo tail

  # Verify: assembled output must equal the gold bytes.
  stderr.writeLine &"covered {covered}/{length} bytes, {instrs.len} instructions, {labels.len} labels"

when isMainModule:
  main()
